### ISSUE TITLE
no password recovery option

### ISSUE THREAD

**Issue by wouteraddink** [DiSSCo/ELViS#10]
#### Description
there is no option yet for password recovery

**Comment by cannedit** [comment]
this ticket is added in Redmine as issue #46708
https://code.pictura-dp.nl/issues/46714

**Comment by Karin-Wiltschke** [comment]
In one of my Computers - if I want to enter the Password for Login, the Suggestion for the email entry covers the field for the password

**Comment by HMHardy** [comment]
I clicked this password link on the login box but did not receive an email although it said one had been sent? In the end I registered again.
So I think although the function is now visible I'm not sure it's working properly?

**Comment by cannedit** [comment]
It always sends an email, but only to email addresses which already have been registered as a user, so which are known in the system; the fact that you could register again means that you were not registered anymore when you tried the password recovery option (for Acceptance we still clear all registered users during a new deployment).
