### ISSUE TITLE
Change institute logo for Luomus

### ISSUE THREAD

**Issue by AnniinaK** [DiSSCo/ELViS#100]
Instead of University of Helsinki logo, use Luomus logo for the Finnish Museum of Natural History Luomus institution page: https://elvis-accept.pictura-hosting.nl/institutions/grid.507626.0

![luomus_en_blue](https://user-images.githubusercontent.com/58849512/76770292-5b2b0700-67a6-11ea-8ad7-cb4118f42726.jpg)

**Comment by cannedit** [comment]
Registered as Redmine issue: 48125
https://code.pictura-dp.nl/issues/48125
