### ISSUE TITLE
file upload error feedback form

### ISSUE THREAD

**Issue by wouteraddink** [DiSSCo/ELViS#101]
#### Description
when I tried to attach a file to the feedback form and pressed submit I got the error:
Something went wrong uploading the form, please try again

that should not happen and the error message should say "uploading the file" not "uploading the form"

the form also gives no indication what type of file or size can be uploaded. By default that could be fairly open, giving an error message only when an attempt is made to upload an unexpected format. I would expect as allowed: images, text files and spreadsheets: png, jpg, txt, xlsx, docx, pptx, odt, csv, rtf. Less than 25MB.

#### Steps to reproduce the issue

1.  attach a file to the upload form
2. press submit
3. 

#### What's the expected result?

-

#### What's the actual result?

-

**Comment by cannedit** [comment]
Registered as Redmine issue: 49053
https://code.pictura-dp.nl/issues/49053

**Comment by wouteraddink** [comment]
I see no change with the previous version. Still get: "Something went wrong uploading the form, please try again" when trying to upload a file.

**Comment by wouteraddink** [comment]
Addition: it did work when I was logged in as requester. In the previous attempt I was logged in as admin.

**Comment by wouteraddink** [comment]
if I attempt to upload a very large file though, it is spinning for a while and then get the same error message: "Something went wrong uploading the form, please try again". I had expected an error message telling me that the file is too big.

**Comment by mtrekels** [comment]
I tested this in issue #96

As requester or VA coordinator it works

![image](https://user-images.githubusercontent.com/52746754/83864984-d1943100-a725-11ea-86dd-c2ffd3f0de23.png)

**Comment by wouteraddink** [comment]
As Maarten commented, it is working better in the costbook upload form (#96), perhaps using different code?

**Comment by cannedit** [comment]
This has been registered in Redmine as issue: 49610
https://code.pictura-dp.nl/issues/49610

**Comment by cannedit** [comment]
This has now been solved on the Acceptance server
