### ISSUE TITLE
improve account disabled email

### ISSUE THREAD

**Issue by wouteraddink** [DiSSCo/ELViS#102]
#### Description

When a sysadmin disables a user account, the user receives an email notification. This notification can be improved, see attached file
![elvis-account-disabled](https://user-images.githubusercontent.com/395870/81172968-88728500-8f9f-11ea-943a-016d61964e0d.png)

**Comment by cannedit** [comment]
The email address incorporation will be taken care of; registered as Redmine issue: 48598; 
Note: the text and lay-out of the email message is aligned with all other email notifications, so improvement of this should be done - if needed - in general and not on an ad hoc basis. 
https://code.pictura-dp.nl/issues/48598

**Comment by cannedit** [comment]
The email address incorporation in the error message is implemented on the Acceptance server now.
