### ISSUE TITLE
improve requests page

### ISSUE THREAD

**Issue by wouteraddink** [DiSSCo/ELViS#104]
#### Description
A requester now sees all requests. I would expect however a separation between my own VA requests and other VA requests. 

Since other requests only need to be shown for VA requests and not for other types of requests, and there will be not many own VA requests, I think this can simply be put on one page, starting with a table with own requests (as "sticky" and then a table with other requests. Only the other requests need sorting and filtering. A more generic implementation would be to have two different tabs, one for My requests and one for Other requests. But it might be better to use tabs for different request types in the future (VA, TA, Loans, Visits). I leave that to the designer.

**Comment by cannedit** [comment]
We are currently working on this: the idea is to put a filter at the top of the page (for requesters as well as VA Coordinators) enbling them to filther "their" and "other" requests.

**Comment by wouteraddink** [comment]
Working ok
