### ISSUE TITLE
Update and sync terminologies

### ISSUE THREAD

**Issue by sharifX** [DiSSCo/ELViS#106]
This is a note is to capture the comments that were given for the pdf manual. 

Terminologies across various ELViS pages need to be synced (for example, "proposer", "requester", "moderator", "coordinator") to avoid confusion.

**Comment by cannedit** [comment]
[ELViS_Manual_20200424_v1+Sandy_WvD.pdf](https://github.com/DiSSCo/ELViS/files/4621468/ELViS_Manual_20200424_v1%2BSandy_WvD.pdf)
As a result of the discussion about the terminology used in ELViS (in the screenshot ELViS manual as attached) we decided to go for some minor text changes:

- VA Call info page: please replace: "proposer", proposal" and: "proposals" in the whole text with: "requester", "request" and: "requests" (see the screenshot attached).
- Institution detail page: please replace: "Institute" with: "Institution" and: "Researchers" with: "People" (see the screenshot attached).
- Request form: please replace: "Request subject" with: "Request title" (see the screenshot attached).
- Comments section of a request: please replace: "Submit" with: "Add comment" (see the screenshot attached).
- Submittance page of a request: please change the capital "S" in the second mentioning of "submittance", please delete the word "peer" and please change "institutes" into: "institutions" (see the screenshot attached).

Registered in Redmine as issue: 49096
https://code.pictura-dp.nl/issues/49096

In due course we will also change the label of the "Submit" button at the end of the requests webform, so also the status "Submitted" in the requests overviews, but we didn't reach consensus about this yet, but candidates are:

- Submit for evaluation/For evaluation
- Forward/Forwarded
- Transfer/Transferred

**Comment by wouteraddink** [comment]
In addition to the already mentioned terminology changes, Sandy mentioned to change "collections" to "participating collections" in the VA Call info page. I think we should adapt that proposal too.

**Comment by wouteraddink** [comment]
And on the homepage: replace applications portal to requests portal

**Comment by cannedit** [comment]
>  
> In addition to the already mentioned terminology changes, Sandy mentioned to change "collections" to "participating collections" in the VA Call info page. I think we should adapt that proposal too.

Yes, correct; that was already in my instructions to the developers (see the screenshot attached), but I forgot to copy that over here.
![ELViS_VACallInfoTextChanges](https://user-images.githubusercontent.com/22167327/81917911-179e1f00-95d6-11ea-8b68-0d659c0a5fb2.png)

**Comment by cannedit** [comment]
> And on the homepage: replace applications portal to requests portal

Sorry, but for this I reacted to that comment from Sandy like this:
"This was put there for the - temporary - 1st VA Call system, but we also have to start supporting TA Calls, so this text has to be changed again anyway (after the 1st VA Call deadline). I would prefer to then go for the caption which is now in the top header: European Loans and Visits System in due time."

And actually I would prefer to go back - in due time - to the original ELViS hompage banner:
![ELViS-banner](https://user-images.githubusercontent.com/22167327/81918464-c2aed880-95d6-11ea-8612-492c6189e3fb.jpg)

**Comment by wouteraddink** [comment]
I agree, that makes sense. In fact I think we can already do that as soon as the code has been forked, that will also show people that we are now working on the full version of ELViS and not on the MVP for the VA call anymore.

**Comment by lisasund** [comment]
@wouteraddink can you test this as well? Scott currently unavailable

**Comment by scottwilson-nhm** [comment]
Hi @lisasund; looking through, I'm happy with this alignment of the terminology. 'Proposals' should be changed to 'Requests' as already flagged in this thread & implemented. 

Happy to mark as resolved!
