### ISSUE TITLE
On registration you should agree with a usage agreement

### ISSUE THREAD

**Issue by wouteraddink** [DiSSCo/ELViS#11]
#### Description
Since we intend to use the user information in the future, to e.g. link the user name to a loan or citation, I think it would be good if the users agree with this on registration.

**Comment by cannedit** [comment]
I would like the WP6 community to come up with the proper text for this (terms of use text); awaiting this the ticket has been added in Redmine as issue #46715
https://code.pictura-dp.nl/issues/46715

**Comment by wouteraddink** [comment]
We can use this privacy statement: https://www.naturalis.nl/en/privacy. However it may be more useful to adopt something similar to https://www.gbif.org/terms/data-user. I will see if I can get advise from a lawyer on this.
