### ISSUE TITLE
status display

### ISSUE THREAD

**Issue by wouteraddink** [DiSSCo/ELViS#110]
#### Description
Although the status display shape is different from buttons, for me the rounded display still looks too much like a button. I get easily confused, especially when the status is displayed in a table where the row highlights when I move over the status displayed in that row. I am not a designer, but I attached an idea for a design that for me looks more like a status.
![being handled status](https://user-images.githubusercontent.com/395870/81955215-18e93f00-960a-11ea-9b66-70192c3749e4.jpg)

**Comment by cannedit** [comment]
I am sorry Wouter, but to me that's more like a button or toggle ...

**Comment by wouteraddink** [comment]
Well as I said I am not a designer, maybe it is more clear if the dot is on the right side or perhaps it needs to have something square rather than rounded. I am sure Michiel will find a solution. This is a minor issue and is not a priority for me but I think at some stage this can be improved.

**Comment by cannedit** [comment]
Since we have introduced this as a "toggle" now (for enabling Admin's to disable requesters), we will not follow up on this for changing the display of the status of a request.
