### ISSUE TITLE
Provide PDF of an approved request + costs calculation documents for Prioritisation Panel

### ISSUE THREAD

**Issue by cannedit** [DiSSCo/ELViS#111]
#### Description
To facilitate the VA Call Prioritisation Panel, it's necessary to provide a zip file per entirely approved request which includes a PDF of the content of the request, plus the calculation documents attached to it.

Sprint target for sprint 13

**Comment by HMHardy** [comment]
Please can you let me know where/how to test this? I cannot see in the acceptance server where to find an approved request to try to generate the zip from? (and per #112 I cannot currently create a request myself). Thanks.

**Comment by cannedit** [comment]
@HMHardy this is Admin functionality, so you can't test this, but Scott Wilson can, he has Admin credentials

**Comment by jmenglund** [comment]
@scottwilson-nhm can you please test this today? Apparently @HMHardy did not have Admin credentials

**Comment by wouteraddink** [comment]
I think scott could not have tested this as there was no approved request. I logged in as a requester, created a new request, then logged in as VA coord and approved. Then I logged in as admin and could download, however t**he downloaded file is saved as .txt which should be .zip**. After I renamed to .zip I could open it. One minor additioinal minor issue: if fields are left empty this is shown in the pdf as "t---".

**Comment by wouteraddink** [comment]
example
[request_9ed80fb8-51aa-4219-be69-fe2482d26bfa.zip](https://github.com/DiSSCo/ELViS/files/4736059/request_9ed80fb8-51aa-4219-be69-fe2482d26bfa.zip)

**Comment by wouteraddink** [comment]
example with empty fields
[request_9f654139-5e96-440f-b38d-6028120aaf3d.zip](https://github.com/DiSSCo/ELViS/files/4736062/request_9f654139-5e96-440f-b38d-6028120aaf3d.zip)

**Comment by cannedit** [comment]
I wasn't able to reproduce this, not in Chrome, nor in Firefox; each time I downloaded a request it was perfectly offered as a zip file, never as a txt file; this might be caused by settings on the computer used, so please try to reproduce this on another machine.
As for the text which indicates fields that were left empty: we can change that, please make a suggestion for what you would like to see instead of "t---".

**Comment by wouteraddink** [comment]
I used Chrome, Windows 7.  I do not have another machine at hand, maybe Scott can test this too. I would change empty fields to "---" without the t.

**Comment by emhaston** [comment]
The ability to download a pdf of a complete request would be useful for all users. Is this going to be possible? Thanks.

**Comment by cannedit** [comment]
@emhaston yes, we will be able to implement that, but for the next version of the tool.

**Comment by wouteraddink** [comment]
PDF looks ok now. Zip file for me still downloads as .txt though instead of .zip. Would be good if Scott or another person with admin access tests this too, as it could be related to my computer.

**Comment by scottwilson-nhm** [comment]
Hi all; I wasn't able to download PDFs on both Edge and Chrome when clicking on the download icon alongside a Request.

**Comment by scottwilson-nhm** [comment]
Okay, I have tried again, this time not using a VPN (at work we use a VPN often to access shared drives).

It downloads now (Edge and Chrome). Please could someone else connect with VPN and see if they encounter the same difficulty? If so perhaps we'll need to add a message to the system asking Admins not to use VPN whilst using ELViS. 

I like the request_overview folder including the constiutent overview and the attached costing template. Thank you for implementing this, is there any way we can make the string of numbers (presumably a unique identifier) in the folder name also be included in the actual filenames within that respective folder?

**Comment by cannedit** [comment]
In case this functionality doesn't work properly when using a VPN then that is caused by a (too) strict VPN configuration which redirects and filters ALL internet communication, not just the internet communication which is aimed at the applications of the company or office. There's nothing we can do about this, nor can we put up a notification for this, because VPN configurations may vary per company/office.

**Comment by cannedit** [comment]
@wouteraddink can you please tell me what the content of the txt file is and whether you can download the txt file, rename the extension from .txt to .zip and then still access the (proper) content of the zip file?

@wouteraddink ah, sorry, I see now that you already answered this question earlier: https://github.com/DiSSCo/ELViS/issues/111#issuecomment-639447476. 

Btw: we think that this change from .txt to .zip is caused by some other software on your machine; if this is true, then any .zip file you download gets this treatment, so in case this also happens when you download the .zip samples you provided over here in your earlier comments (https://github.com/DiSSCo/ELViS/issues/111#issuecomment-639449115 and https://github.com/DiSSCo/ELViS/issues/111#issuecomment-639449718) then that's prove that this not only happens to you when using ELViS, but for example also when you use Github. For the record: I can see and download these sample files you provided here as .zip files.

So I guess this issue is resolved now?

**Comment by wouteraddink** [comment]
The files here are saved as .zip when I download them. If I download zip files from a site like http://catalogueoflife.org/content/annual-checklist-archive then these are also downloaded as .zip.

**Comment by cannedit** [comment]
Ok, Wouter, thank you for confirming this; it's still strange, but since you are the only person experiencing this (from testers with admin credentials), I think it's not a structural problem, so it's Ok.
