### ISSUE TITLE
Possibility to delete draft requests by their original requester and by an admin

### ISSUE THREAD

**Issue by cannedit** [DiSSCo/ELViS#112]
#### Description
To avoid polluting the system with too many draft requests, it should be possible for requesters to delete their own requests when they are still in "draft" status.

Since most of the draft requests in the ELViS production server were caused by the fact that a draft request gets registered the minute one opens the request form, and people were curious to take a peek at the ELViS functionality like that, we will make sure that a draft request will only be registered once at least a title is provided.

In case requesters visited the ELViS tool only once, created some draft requests out of curiosity and didn't intended to come back to handle these draft requests anymore, it should be possible for an admin to also delete draft requests. 

Sprint target for sprint 13

**Comment by vixriihi** [comment]
As a requester deleting drafts seems to work just fine (don't have admin account so cannot test that part)

**Comment by vixriihi** [comment]
only minor detail that I found is that when you delete, spinner shows up on the request list, but I'm still able to click the trashcan icon and re-delete the request. End result still is that the deleted item is cone so it's not that big of a deal (second delete request just fails).

**Comment by HMHardy** [comment]
Sorry I can't test this as today the system will not let me create a request in order to then delete it (I cannot move beyond the first page despite entering test content in all fields).

**Comment by cannedit** [comment]
@HMHardy I just entered the Acceptance server with my own 'normal' user registration and I was able to create a draft request without a problem, so I can't reproduce this; maybe you can create another user account, using another email address, and try to reproduce it? I am sorry for the inconvenience.

**Comment by B-San-Chi** [comment]
I have also created a draft and deleted it without problems, it seems that this tool works correctly.

**Comment by cannedit** [comment]
@vixriihi about the minor detail you mentioned: could you please - or somebody else - check this again and try to reproduce this, because it might have been caused by problems with internet connection or server load; I can't reproduce this at my end.

**Comment by B-San-Chi** [comment]
I think that it must have been a problem with your internet connection. At least in my case, it is permanently deleted. I have done another test and no spinner appears and I can not access to the trash icon again.

**Comment by HMHardy** [comment]
I logged out and in again and can now create a request ok and see the list (previously the first page was not managing to save my request and produce the information on the right hand side - or at least there was a very large lag time in this). I have pressed the delete icon but now nothing is happening with that (it's been about 10 minutes and I have tried refreshing the list). Will try again later.

**Comment by HMHardy** [comment]
I am getting a spinner flashing up periodically but nothing happening. I cannot tell whether the trash icon is active or not, it looks a bit 'grey' and the same on all requests whether they are mine or not, is that how it's supposed to look?

**Comment by B-San-Chi** [comment]
Now I don't see anything, all the requests that were there 5 minutes ago have disappeared

**Comment by jmenglund** [comment]
@scottwilson-nhm We need someone with the admin role to test this. Do you think you can do this today?

**Comment by vixriihi** [comment]
> @vixriihi about the minor detail you mentioned: could you please - or somebody else - check this again and try to reproduce this, because it might have been caused by problems with internet connection or server load; I can't reproduce this at my end.

Yes that still occurs. Requires slow connection (tested with slow mobile connection)

**Comment by wouteraddink** [comment]
tested when logged in as admin and works fine.

**Comment by jmenglund** [comment]
@scottwilson-nhm since @wouteraddink has already tested this now, you don't have to test the admin aspects of this issue!

**Comment by HMHardy** [comment]
I have tried again on the call today to delete the test request I created last week, by clicking the 'bin' icon which shows as grey on the request list -  but nothing is happening still.

**Comment by wouteraddink** [comment]
For me this works still fine. Might need to check with Helen again?

**Comment by scottwilson-nhm** [comment]
I am able to delete requests but have the same non-responsive issue when I'm using the NHM VPN.

When I am using VPN, nothing happens. When I am not, a pop-up appears which allows me to delete a request and the request is deleted immediately. 

@HMHardy - have you tried with VPN disconnected? It would be interesting to know if 1. this is just me or an NHM-wide, issue, and 2. if other institutional VPNs have the same problem. @emhaston could you try with your RGBE? 

Otherwise delighted this functionality is being implemented; much of my data scraping for VA Call 1 has been wading through these empty drafts!

**Comment by cannedit** [comment]
In case this functionality doesn't work properly when using a VPN then that is caused by a (too) strict VPN configuration which redirects and filters ALL internet communication, not just the internet communication which is aimed at the applications of the company or office. There's nothing we can do about this, nor can we put up a notification for this, because VPN configurations may vary per company/office.

**Comment by HMHardy** [comment]
As noted in this morning's meeting, now when I try to delete (not on VPN) i am taken to the new request title screen. My previous request remains in the request list when I navigate back there. I will try to test this as discussed in other browsers/other machine.

**Comment by HMHardy** [comment]
Now tested in Edge on the same machine - clicking the bin icon in the request list take me through to the details of the request, with no obvious way to delete it. It remains in the list when I navigate back.

**Comment by HMHardy** [comment]
And now tested in Safari on my phone (so different machine) - this again takes me to the full request details with no obvious way to delete.

**Comment by cannedit** [comment]
@HMHardy Ok, this is strange, but apparently you are the only tester experiencing this; maybe you could - as a last attempt - try one more thing: create another account, using another email address, and then try testing this again, as it could be related to a problem with your current account.

**Comment by HMHardy** [comment]
I have just registered separately with my gmail address and am getting the same result. What should I see when I click the 'bin' icon? It would be useful to know what should happen. Currently when I click it it just opens the request again which I am assuming is not right?

**Comment by cannedit** [comment]
@HMHardy please see the video attached here.

Note: the longer list you see after the actual deletion of a draft request, is a bug which is already reported here as issues #131 and #132 and will be dealt with ofc.
[TestingELViS_DeletingDraftRequests2.zip](https://github.com/DiSSCo/ELViS/files/4820226/TestingELViS_DeletingDraftRequests2.zip)

**Comment by HMHardy** [comment]
Thanks Wim sorry this comment is late - the video is useful, I see that my problem is I have never actually had an active 'delete' icon by my test requests - i.e. I have never had this with the black margin, only 'greyed out' as it is for other requests, so that clicking on it just has the same effect as clicking on the request itself.
