### ISSUE TITLE
Possibility for requesters and VA Coordinators to filter own/other requests

### ISSUE THREAD

**Issue by cannedit** [DiSSCo/ELViS#113]
#### Description
Since requesters and VA Coordinators now have the possibility to see all requests from others (either other requesters or requests related to other institutions) in the main menu option "Requests", it is necessary to offer them a filter via which they can choose to either see their own requests and requests related to their own institution, or other requests, from other requesters (except the ones still in the draft status ofc) or only related to other institution than their own.

Sprint target for sprint 13

**Comment by FB-MfN** [comment]
As VA coordinator I cannot see all requests. Just the request related to my institution is visible.
As a requester I an see all request, but they are all listed as "My requests"

**Comment by cannedit** [comment]
Hi, that functionality is not available for VA Coordinators yet, so hence it's not up for testing yet; it's the sprint target we didn't manage to finish yet because of a problem with the filtering and pagination that would come along with implementing this functionality for VA Coordinators also; hopefully we will manage to solve the problem in the coming weeks.

**Comment by emhaston** [comment]
Hi, tested this and it works for me.
