### ISSUE TITLE
Misaligment actions column

### ISSUE THREAD

**Issue by mtrekels** [DiSSCo/ELViS#114]
#### Description
The Actions column seems to be shifted upwards.

#### Steps to reproduce the issue

1.  Use Google chrome (laptop screen)
2. Go to the Requests tab
3. 

#### What's the expected result?

- actions should be aligned with the requests

<img width="910" alt="misalignment_actions" src="https://user-images.githubusercontent.com/52746754/83764152-de5b4b00-a679-11ea-99f2-6ab1d1c5b4d5.png">

**Comment by cannedit** [comment]
Yes, I can reproduce that and not only in Chrome, it also happens in Firefox; I think it has something to do with long request titles and with responsiveness (see the screenshots attached). We will take care of this.

![ELViS_Requests_Chrome](https://user-images.githubusercontent.com/22167327/83803614-319ac100-a6ad-11ea-8a1c-7ea6599b1555.png)
![ELViS_Requests_Firefox](https://user-images.githubusercontent.com/22167327/83803616-32335780-a6ad-11ea-80bc-31e095179d7d.png)
![ELViS_Requests_Firefox_narrow_screen](https://user-images.githubusercontent.com/22167327/83803617-32cbee00-a6ad-11ea-8c53-2d441389e3e5.png)

**Comment by cannedit** [comment]
This is registered in Redmine as issue 49593
https://code.pictura-dp.nl/issues/49593

**Comment by mtrekels** [comment]
Tested. Issue seems to be resolved.

OK to close
