### ISSUE TITLE
Disappearing field value

### ISSUE THREAD

**Issue by vixriihi** [DiSSCo/ELViS#115]
#### Description
When making a request "Abstract" and "Other requesters involved (name, email address and ORCID iD)" can disappear just by clicking the "Request title" field and out of it

#### Steps to reproduce the issue

1. Create new request
2. type something to "Request title",  "Abstract" and "Other requesters involved..." fields
3. click "Request title" field
4. click outside of "Request title" field

#### What's the expected result?

- "Abstract" and "Other requesters involved..." fields would have the values inputted

#### What's the actual result?

- "Abstract" and "Other requesters involved..." fields are cleared

edit: doing this seems to copy the request also (see the screenshot)

![image](https://user-images.githubusercontent.com/5203261/83834893-1608d800-a6f8-11ea-8863-89fa2f052aa6.png)

**Comment by cannedit** [comment]
This is registered in Redmine as issue 49594
https://code.pictura-dp.nl/issues/49594

**Comment by vixriihi** [comment]
Now I don't see any other fields than the "Request title" and there is no way of getting forward

![image](https://user-images.githubusercontent.com/5203261/85358419-610a5400-b51c-11ea-8089-0174cfa97c85.png)

**Comment by vixriihi** [comment]
Had to press enter ~5 times before the other fields appeared and that must have caused a duplicate in the list
![image](https://user-images.githubusercontent.com/5203261/85358686-08878680-b51d-11ea-80fe-7d76a773da71.png)

**Comment by vixriihi** [comment]
After first failed attempt this seems to work fine. However I'm able to reproduce the extra enter requirement by
1. opening the testing site in incognito window
2. login
3. Create new request
4. enter title
5. press enter
First enter nothing seems to happen (other fields stay hidden) but empty request title appears to the list. Second enter shows the fields (if you press enter quickly few times in the title field it will create other duplicates also)

**Comment by cannedit** [comment]
@vixriihi thank you for your remarks on issue #124, that one is mainly due to people not logging out when they are done working in ELViS, so that causes problems with new functionality not kicking in properly when they start using ELViS again and we will try to take care of this, but can you please also test the original issue reported here?

**Comment by vixriihi** [comment]
np :)
I did try to test the original case and the result was: https://github.com/DiSSCo/ELViS/issues/115#issuecomment-647888940
After the first try everything is working (so I guess this could be accepted...)
(steps in https://github.com/DiSSCo/ELViS/issues/115#issuecomment-647896641 should allow to repro the empty page)
