### ISSUE TITLE
Every user can access request in draft state

### ISSUE THREAD

**Issue by vixriihi** [DiSSCo/ELViS#116]
#### Description
Not 100% sure if this is intended or not but seems like at least here we can access each others requests when they are in draft state.
https://elvis-accept.pictura-hosting.nl/calls/7d4cc4af-ac72-406e-b128-0edb23e48659/new-request/7de3397a-3590-4659-ae8a-842daf71249b

#### Steps to reproduce the issue

1.  Make a new request. 
2. copy the link to same one

#### What's the expected result?

- others would not see the request in draft state

#### What's the actual result?

- others can see the request in draft state

**Comment by cannedit** [comment]
This will probably not be abused much in practice, but I have nevertheless registered this as a bug in Redmine: https://code.pictura-dp.nl/issues/49599
