### ISSUE TITLE
strange behavior editing other requests

### ISSUE THREAD

**Issue by wouteraddink** [DiSSCo/ELViS#119]
#### Description
logged in as requester, I can see requests from others that are being handled. It looks though if I can not only see them but also edit them. However if I press update, the changes are not saved (luckily). But if I change the title, I suddenly end up in a new request made by me, with the new title.

I would expect that I see the requests submitted by others as read-only.

**Comment by cannedit** [comment]
This is registered in Redmine as issue 49601
https://code.pictura-dp.nl/issues/49601
