### ISSUE TITLE
as admin I do not see a new approved request

### ISSUE THREAD

**Issue by wouteraddink** [DiSSCo/ELViS#121]
#### Description

I added a new VA request as requester, approved this as VA coordinator, the status is now approved but I do not see it in the list with requests if I login as admin. The request is 67fcfef2-8b23-4b2a-8c5f-f98af8f4e697 (digitise bat specimen). I deleted the drafts in the request list to make sure there were not too many requests in the list but with only 9 requests left I still do not see it as admin. I see it though when logged in as VA coord or requester.

**Comment by mnwdeboer** [comment]
I created an issue for this. Bug #49677

**Comment by cannedit** [comment]
I can reproduce this, see screenshots below:

![ELViS_Github-issue-121a](https://user-images.githubusercontent.com/22167327/84671829-1c812600-af28-11ea-8163-6e4c01882a18.png)
![ELViS_Github-issue-121b](https://user-images.githubusercontent.com/22167327/84671831-1d19bc80-af28-11ea-947c-587954ee5483.png)

**Comment by wouteraddink** [comment]
seems to be ok now.
