### ISSUE TITLE
New VA request not visible

### ISSUE THREAD

**Issue by emhaston** [DiSSCo/ELViS#122]
#### Description
![image](https://user-images.githubusercontent.com/6713716/84128494-956c1380-aa38-11ea-84d2-4269f3f0f60b.png)

Received an e-mail with a new VA request but this is not visible when I click on the link. I seem to be logged in as the VA Coordinator, but the Requests tab page is blank.

A new VA request for your Institution has been created in ELViS
Dear Elspeth Haston,

In the European Loans and Visits System (ELViS) a new VA request for the institution “Royal Botanic Garden Edinburgh” for which you are VA Coordinator has been submitted Please go to: https://elvis-accept.pictura-hosting.nl/requests/67fcfef2-8b23-4b2a-8c5f-f98af8f4e697 to evaluate this request..

Best wishes,

Administrator European Loans and Visits System (ELViS)
For questions please contact: synthesys@nhm.ac.uk 

#### Steps to reproduce the issue

1.  Click the link in the e-mail
2. Check that I'm logged in
3. No request is visible in the Requests tabl

#### What's the expected result?

- I would expect to see a request to review.

#### What's the actual result?

- No requests visible

**Comment by emhaston** [comment]
![image](https://user-images.githubusercontent.com/6713716/84129457-e0d2f180-aa39-11ea-888f-a06ddba3a914.png)

**Comment by emhaston** [comment]
When I logged in with my Requester account I can see 12 requests, including the test ones. I would have expected most of these to have gone to my VA Coordinator account.

![image](https://user-images.githubusercontent.com/6713716/84130964-d74a8900-aa3b-11ea-807a-461a93a90418.png)

**Comment by mnwdeboer** [comment]
Created an issue fo this. (Bug #49678)

**Comment by cannedit** [comment]
Hi Elspeth,

I am sorry, but I can't reproduce this using your VA Coordinator credentials (see the screenshots below), so would you please check this again?

![ELViS_Github-issue-122a](https://user-images.githubusercontent.com/22167327/84671673-f196d200-af27-11ea-9704-54c55e31cb57.png)
![ELViS_Github-issue-122b](https://user-images.githubusercontent.com/22167327/84671678-f22f6880-af27-11ea-83f8-8b6247c8fd01.png)

**Comment by emhaston** [comment]
I'm now seeing them here. No idea what went wrong, but it seems okay now.
