### ISSUE TITLE
sorting requests by date is not working properly

### ISSUE THREAD

**Issue by wouteraddink** [DiSSCo/ELViS#123]
#### Description
the table of requests can be sorted by column, one of these columns is the date. Sorting should result in either sorting from old to new or new to old. The list is not sorted correctly, see screenshot

![elvis request sorting](https://user-images.githubusercontent.com/395870/85147216-d3461480-b24e-11ea-87a5-af71451403d1.jpg)

**Comment by cannedit** [comment]
This is registered in Redmine as issue: 49864
https://code.pictura-dp.nl/issues/49864

**Comment by cannedit** [comment]
This has now been solved on the Acceptance server
