### ISSUE TITLE
cannot change title of a request anymore

### ISSUE THREAD

**Issue by wouteraddink** [DiSSCo/ELViS#125]
#### Description

With the refactored VA request form it is no longer possible to change the title while in draft or submitted for evaluation. It might however be needed to change the title, for instance if comments indicate it ast necessary for a requester to merge his/her request with a request from another requester.

**Comment by cannedit** [comment]
This is registered as Redmine issue: 49888
https://code.pictura-dp.nl/issues/49888

**Comment by cannedit** [comment]
This has now been solved on the Acceptance server
