### ISSUE TITLE
add checkbox for agreement

### ISSUE THREAD

**Issue by wouteraddink** [DiSSCo/ELViS#126]
#### Description

The refactored VA request makes it possible to show, together with the title field and before showing the rest of the form, to add a checkbox "I agree with my request being publicly available after submission for evaluation." I think adding such an explicit consent would be a good addition, might even be necessary for GDPR and avoids misunderstandings.

**Comment by cannedit** [comment]
Actually I think this should be taken care of in general for the ELViS tool, for example via a usage agreement, for which I am still waiting for some text (see [Github issue 11](https://github.com/DiSSCo/ELViS/issues/11)).

**Comment by cannedit** [comment]
This has been taken care of in the ELViS version 0.6.0, released on the Acceptance server on 15/01/2021.
