### ISSUE TITLE
approved request still has submit button for evaluation

### ISSUE THREAD

**Issue by wouteraddink** [DiSSCo/ELViS#129]
#### Description
I think once a request has been approved the submit section with button for evaluation should not be shown anymore.

**Comment by cannedit** [comment]
In fact that part of the request form can be suppressed the moment the request form is submitted. 

It's not a bug and I can't promise whether we can deal with this on short notice, but I have registered it in Redmine as issue 49865: https://code.pictura-dp.nl/issues/49865

**Comment by cannedit** [comment]
This is resolved during the last deployment.
