### ISSUE TITLE
registration steps not well aligned on mobile

### ISSUE THREAD

**Issue by wouteraddink** [DiSSCo/ELViS#13]
#### Description

on mobile the registration steps are sometimes two lines of text and then the vertical thread with bullets is not well aligned. Minor issue.

#### Additional details / screenshot
![Screenshot_20200102_174436_com android chrome](https://user-images.githubusercontent.com/395870/71679788-b8f3a980-2d88-11ea-8781-9afc2d961281.jpg)

**Comment by cannedit** [comment]
this ticket is added in Redmine as issue #46716
https://code.pictura-dp.nl/issues/46716
