### ISSUE TITLE
Deleting an item breaks the "Show only my requests" selection

### ISSUE THREAD

**Issue by vixriihi** [DiSSCo/ELViS#131]
#### Description
On the requests page if I have selected "Show only my requests" and delete an item. The list that I see after the deletion ignore the selection I made earlier.

#### Steps to reproduce the issue

1.  Go to requests page
2. Click "Show only my requests"
3. Delete an item

#### What's the expected result?

- list would still show only my requests

#### What's the actual result?

- list shows a list like the "Show all requests" select would be selected

#### Additional details / screenshot

![image](https://user-images.githubusercontent.com/5203261/85387984-346f3000-b54e-11ea-93e1-36ea06876858.png)

**Comment by cannedit** [comment]
This is registered in Redmine as issue: 49887
https://code.pictura-dp.nl/issues/49887

**Comment by cannedit** [comment]
The issue you registered as #132 is related to this.

**Comment by vixriihi** [comment]
Last time I added too many in one task so I tried to separate things this time :)
I first noticed this issue, but in the description I chose little not so well describing words sry (I'll edit it a little to better reflect)

**Comment by cannedit** [comment]
This has now been solved on the Acceptance server
