### ISSUE TITLE
After deleting I can see others draft that I didn't previously see

### ISSUE THREAD

**Issue by vixriihi** [DiSSCo/ELViS#132]
#### Description
For some reason when I delete I can see more requests than I saw before

#### Steps to reproduce the issue

1.  Go to requests page
2. delete request

#### What's the expected result?

-still see only requests that I have access to (minus the one just deleted :))

#### What's the actual result?

-I can see those that I'd expect and them some more.
For example in my list there was no Wims request "[Test Request for Request without institution being selected](https://elvis-accept.pictura-hosting.nl/requests/242c7b61-2a51-4b90-815b-219f25786a6d)", but after deleting my own item it appears on the list and I'm able to access it

#### Additional details / screenshot

before delete
![image](https://user-images.githubusercontent.com/5203261/85388773-2d94ed00-b54f-11ea-963d-d5d0f4fbdb58.png)

after delete
![image](https://user-images.githubusercontent.com/5203261/85388840-41d8ea00-b54f-11ea-9655-94e5e794d0cc.png)

**Comment by cannedit** [comment]
This is related to the bug you registered as issue #131.

**Comment by RBGE-Herbarium** [comment]
I get the same but when I click on Show all Requests I only see the expected subset again, and then when I click again on Show my Requests I see the expected subset.


![image](https://user-images.githubusercontent.com/63307210/85403504-5fa94d80-b555-11ea-919e-43a57499fc37.png)

![image](https://user-images.githubusercontent.com/63307210/85403580-87001a80-b555-11ea-8cdf-e4149abd1d02.png)

![image](https://user-images.githubusercontent.com/63307210/85403604-92ebdc80-b555-11ea-840b-c06c3a8de1e2.png)

**Comment by cannedit** [comment]
@RBGE-Herbarium yes, that's what I noticed too, but the first (automatic) refresh of the page "Show only my requests" should show the right, updated overview ofc; I don't think this is hard to solve, so we will take care of this.

**Comment by vixriihi** [comment]
just a side note: Not sure if it was clear from the description but this don't require you to first select "Show only my requests" to see this effect (toggling the show all requests and show only my requests does clear the effect).

**Comment by cannedit** [comment]
This has now been solved on the Acceptance server
