### ISSUE TITLE
Admin/Institution Moderator Functionality: Editing Institutions information

### ISSUE THREAD

**Issue by cannedit** [DiSSCo/ELViS#134]
New ELViS functionality to be tested on the Acceptance server (check the additional functionality manual for details)

**Comment by philippeloret** [comment]
I won't be able to test these features because I didn't have admin role.

**Comment by wouteraddink** [comment]
when trying to edit a institution as moderator I get an error 403 access denied error: Sadly you don't have permission to access this content...

**Comment by cannedit** [comment]
Sorry, I can't reproduce this, so with what account (your admin account or the general moderator account) and for which institution were you trying to perform this action and in what browser?

**Comment by wouteraddink** [comment]
General moderator account, Meise institution, chrome browser

**Comment by cannedit** [comment]
Sorry, I still can't reproduce this (see the video in the zip attached), so it must be some sort of hick-up at your end.

[ELViS_GithubIssue_134.zip](https://github.com/DiSSCo/ELViS/files/5659770/ELViS_GithubIssue_134.zip)

**Comment by philippeloret** [comment]
I have also a 403 error (Forbidden) when I want to edit institution with the moderator general account.

![elvis_edit_institution](https://user-images.githubusercontent.com/75371870/101497555-6264f700-396b-11eb-8982-a1f131440d9d.jpg)

I used firefox / ubuntu.

#### Steps to reproduce the issue

1. Click on 'Agentschap Plantentuin Meise' institution
2. Click on 'Edit institution' button
3. Click on 'Contact person' then 'Contact person email'

Then the dialog box (403 error) appears...

**Comment by wouteraddink** [comment]
in the video I did not see an attempt to edit, only a selection of the edit form. The problem occurs when trying to edit a value.

**Comment by cannedit** [comment]
Ok, correct, so this is indeed a bug, we will take care of this.

**Comment by cannedit** [comment]
We have solved this, so please test again.

**Comment by philippeloret** [comment]
I cannot test. Moderator general account does not have theses privileges anymore.

**Comment by cannedit** [comment]
@philippeloret you can still use the general moderator account for testing this, but this account is now only connected to the NHM/London institution, so using this account you can't edit all institutions anymore; for testing this for other institutions, the VA Coordinators of the institutions now have Institition Moderator permissions for their own institution.

**Comment by mtrekels** [comment]
Tested for Meise Botanic Garden: OK
