### ISSUE TITLE
Admin/Institution Moderator Functionality: Creating/Editing/Deleting Facilities

### ISSUE THREAD

**Issue by cannedit** [DiSSCo/ELViS#135]
New ELViS functionality to be tested on the Acceptance server (check the additional functionality manual for details)

**Comment by philippeloret** [comment]
I won't be able to test these features because I didn't have admin role.

**Comment by wouteraddink** [comment]
when trying to edit a facility as moderator I get an error 500 when trying to select a facility address: the server encountered a temporary error and could not complete your request. Please refresh the page or try again in 30 seconds...
Field `facilityAddress` not found

**Comment by wouteraddink** [comment]
as moderator I would also expect edit buttons in the overview lists of facilities and institutions for the ones I am allowed to edit.

**Comment by cannedit** [comment]
Sorry, the fetching of an address for a facility wasn't supposed to be in this deployment yet because it's not finished yet (it indeed generates a 500 server error and we need to fix this); this will be availble in a next deployment.

Adding maintenance buttons in the overview of the facilities is an enhancement in the category 'nice to have', so we will not implement this for now.

**Comment by mmarschler** [comment]
Just logged in with the moderator@picturae.com-account to test the moderator functionality. I tested creating/editing/deleting facilities. Everything worked fine (except selecting the institutional address, which is already known) and it is very userfriendly! I also tested the search-function in the facilities-tab in the main menu - it also works perfectly well. 

A little note: On the map in the Institutions tab, the position of the NHMW does not reflect the actual location of the museum, although the institutional address is entered correctly.

**Comment by cannedit** [comment]
@mmarschler thank you for your feedback; yes, we are taking care of the fetching address issue and we will also take care of showing the proper location in the Google map.

**Comment by mmarschler** [comment]
Selecting a facility address works now! But in the drop-down list, there is one more address shown that is not associated with the NHMW (i. e., Cromwell Road London).

**Comment by cannedit** [comment]
@mmarschler that must have been a glitch, I just checked and didn't see that London address when trying to create a new facility for NHMW, so could you please check again and maybe fetch me some screenshots in case it happens again?

**Comment by mmarschler** [comment]
@cannedit You're right, the third address vanished. Everything is fine now. Thanks Wim.

**Comment by B-San-Chi** [comment]
For the Real Jardín Botánico, Madrid:
I have already included the correct address. Now we need to include the map with the location.

**Comment by cannedit** [comment]
That should be updated automatically after changing an address, so please keep an eye on this.

**Comment by B-San-Chi** [comment]
ok. but there has never been anything

**Comment by cannedit** [comment]
Well, the Google map shows on our Test server and on the Production server, so there must be something wrong with it on the Acceptance server. We will take a look at it.

**Comment by B-San-Chi** [comment]
Thanks

**Comment by cannedit** [comment]
@B-San-Chi the Google Map for the Real Jardín Botánico, Madrid is available now, please test.

**Comment by B-San-Chi** [comment]
Hi Wim,
Here attached are the correct location for the RJB
Thanks,
Begoña

----- Mensaje de Wim van Dongen <notifications@github.com> ---------
      Fecha: Mon, 01 Feb 2021 07:58:57 -0800
         De: Wim van Dongen <notifications@github.com>
Responder-A: DiSSCo/ELViS  
<reply@reply.github.com>
     Asunto: Re: [DiSSCo/ELViS] Admin/Institution Moderator  
Functionality: Creating/Editing/Deleting Facilities (#135)
       Para: DiSSCo/ELViS <ELViS@noreply.github.com>
         Cc: Begoña Sánchez Chillón <bego@mncn.csic.es>, Mention  
<mention@noreply.github.com>

>  
>
>   @B-San-Chi[1] the Google Map for the Real Jardín Botánico, Madrid  
> is available now, please test.
>
>   —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub[2], or unsubscribe[3].

----- Terminar mensaje de Wim van Dongen <notifications@github.com> -----



Vínculos:
---------
[1] https://github.com/B-San-Chi
[2] https://github.com/DiSSCo/ELViS/issues/135#issuecomment-770961165
[3]

**Comment by B-San-Chi** [comment]
I don't know if you can see the attached file. There is the correct location of the RJB
[RJBmap.docx](https://github.com/DiSSCo/ELViS/files/5909714/RJBmap.docx)

**Comment by cannedit** [comment]
Hi @B-San-Chi,
I am sorry, I don't understand: is the location shown now correct?

**Comment by B-San-Chi** [comment]
No. I already sent you the real location in an attach file

The place on the map where you are now is on the outskirts of the city. The RJB is in the center of Madrid, in Plaza de Murillo, 2, occupying the square with the Prado Museum. Postal code 28014

 

 

 

De: Wim van Dongen [mailto:notifications@github.com] 
Enviado el: jueves, 04 de febrero de 2021 10:28
Para: DiSSCo/ELViS
CC: Begoña Sánchez Chillón; Mention
Asunto: Re: [DiSSCo/ELViS] Admin/Institution Moderator Functionality: Creating/Editing/Deleting Facilities (#135)

 

Hi @B-San-Chi <https://github.com/B-San-Chi> ,
I am sorry, I don't understand: is the location shown now correct?

**Comment by LarissaS** [comment]
It works fine, I've tried adding, editing, removing facilities and instruments. But when adding a new facility, I had a problem: 
my description of the facility was quite long and it was cut in the middle without telling me that it exceeded  the allowable length of the text. Can this field (Description)  consist of only 200 words? 
It may be a problem if the list of facilities is added automatically. If I have to add it manually I can indeed split it into separate services. 
![image](https://user-images.githubusercontent.com/949726/107039154-cc5c1a00-67bd-11eb-86d4-5900c142a863.png)

**Comment by B-San-Chi** [comment]
The location map for the Real JArdín Botánico de MAdrid now is correct.
Thank you!!!!

**Comment by mmarschler** [comment]
The location of the NHMW is now correct too.

**Comment by B-San-Chi** [comment]
I have the same problem than LarissaS, there is not enough space neither in the description of the laboratory nor of the instrumentation

**Comment by cannedit** [comment]
I am sorry we have to stick to the 2000 character limit, so please try to solve this via linking to a webpage which will provide more info.
