### ISSUE TITLE
VA Call/Request functionality

### ISSUE THREAD

**Issue by cannedit** [DiSSCo/ELViS#136]
'Old' already existing ELViS VA Call functionality, completely refactored, so to be tested again on the Acceptance server (check the 'old' manual for details)

**Comment by philippeloret** [comment]
An internal server error (dialog box) occurred when I submitted for the first time my requests as a requester. It seems that requests were actually submitted. The requests were 'This is a test' and 'This is another test'.

**Comment by B-San-Chi** [comment]
to me It is happened exactly the same

**Comment by HMHardy** [comment]
Where requesters enter a request title then have to press Enter/Return, it would be more self-explanatory to have a 'next' or arrow button or to just show everything to begin with. There is no way to know you should press return without reading the manual.
As above I get server error 500 when pressing 'submit', followed by endless rotation of the time wheel in the yellow submit button, but my request (TEST - HH) shows under requests menu as having been submitted .

**Comment by mmarschler** [comment]
Same here - error 500 when pressing submit & a "next"-button after filling in the request title would be very helpful.

**Comment by cannedit** [comment]
The 500 server error when submitting a request is a bug and will be dealt with.

The issue of how to continue after testing is an enhancement, after all it says: "Fill in a title first and presse enter" in the text field before entering a title (the same functionality is active for creating facilities); but we will think of something to make this more obvious.

**Comment by mtrekels** [comment]
The error remains at first submission (see screenshot)

The request seems to be submitted though, since the next time, the action is 'Update Request'

![image](https://user-images.githubusercontent.com/52746754/102762728-f88c1a80-4378-11eb-9213-a74beea036fe.png)

**Comment by sharifX** [comment]
I had the same error. But the request was submitted. When I clicked 'ok' (from the 500 Error screen), the submit button showed a spinning wheel. 

![image](https://user-images.githubusercontent.com/50382675/102796129-16c03d80-43ae-11eb-83b2-e0bd4a749216.png)

**Comment by philippeloret** [comment]
I had an internal server error and the request was submitted.

**Comment by B-San-Chi** [comment]
The request have been submited

**Comment by B-San-Chi** [comment]
The error does not appears and the request is submitted

**Comment by jgrieb** [comment]
I also tested this today, after registering as a new user (so it was the first request as a new user) and the request was submitted without error. Submission seems to work well now.
