### ISSUE TITLE
Error when entering the website

### ISSUE THREAD

**Issue by wouteraddink** [DiSSCo/ELViS#137]
#### Description
first time when I entered the website through chrome on my laptop and on my phone I got an error, I think a 404 page. When copying the link from Lisa's email it was working though and then stayed working. Maybe it needed the slash at the end the first time, I could not spot any other difference. 

However on MS Explorer I get a real error: "Can’t connect securely to this page. This might be because the site uses outdated or unsafe TLS security settings. If this keeps happening, try contacting the website’s owner. Your TLS security settings aren’t set to the defaults, which could also be causing this error."

**Comment by wouteraddink** [comment]
the 404 error seems to happen when entering http:// instead of https://, it seems not to redirect automatically the first time. The error in MS Explorer may be something different
![elvis_screenshot2](https://user-images.githubusercontent.com/395870/100875574-7b226800-34a6-11eb-916d-aadfab5fb62f.jpg)

**Comment by philippeloret** [comment]
There is no SSL certificate for the website and browsers don't accept that.

**Comment by cannedit** [comment]
Which version of MS Explorer did you use to get this error? Some versions of MS Explorer are not supported anymore and MS itself recommends Edge ...

**Comment by wouteraddink** [comment]
Sorry it is called Edge now. I used Microsoft Edge for Windows 10, build 44.18362.449.0 on a new Windows 10 installation.

**Comment by cannedit** [comment]
Ok, I noticed it too now, but this will be solved once we will deploy on production, because over there this is not an issue as far as I can see, Ok?
