### ISSUE TITLE
Error when trying to register an existing user

### ISSUE THREAD

**Issue by wouteraddink** [DiSSCo/ELViS#138]
When trying to register a user with email address that already exists, an error 400 is shown (bad request). In principle it should generate an error, but something like: this user already exists.
![elvis_screenshot1](https://user-images.githubusercontent.com/395870/100875784-c472b780-34a6-11eb-93e0-96530d5624ab.jpg)

**Comment by philippeloret** [comment]
I do the same and I had the same result.

**Comment by cannedit** [comment]
This is indeed not the right error message, we will change this.

**Comment by cannedit** [comment]
This has been taken care of in the ELViS version 0.6.0, released on the Acceptance server on 15/01/2021.

**Comment by mmarschler** [comment]
It works now. I'm not able to use an email address that already exists.
![ELViS_email_exists_2021-02-08](https://user-images.githubusercontent.com/75616869/107217302-471b7400-6a0e-11eb-9671-ad89303d3887.PNG)
