### ISSUE TITLE
menu not fully visible on mobile

### ISSUE THREAD

**Issue by wouteraddink** [DiSSCo/ELViS#14]
#### Description
after login on a mobile device, the menu is show at the bottom and not fully visible see screenshot.

#### Additional details / screenshot

![Screenshot_20200102_174850_com android chrome](https://user-images.githubusercontent.com/395870/71679894-efc9bf80-2d88-11ea-8437-9ba1a4f089dd.jpg)

**Comment by cannedit** [comment]
this ticket is added in Redmine as issue #46716
https://code.pictura-dp.nl/issues/46716
