### ISSUE TITLE
people can currently register without email validation

### ISSUE THREAD

**Issue by wouteraddink** [DiSSCo/ELViS#140]
#### Description
people can currently register without email validation (and there is no email confirmation sent). This makes vandalism by bots etc very easy.

**Comment by cannedit** [comment]
Email confirmation is not sent at the moment because of problems with the mail server for the acceptance server; this will be dealt with soon.

**Comment by emhaston** [comment]
Has this been resolved yet? Our testing of a new registration resulted in no e-mail being received. This means that the user does not realise that the registration has actually worked.

**Comment by cannedit** [comment]
No, sorry, but we are still facing problems with the mailserver on our Acceptance server, but this will not be a problem on the Production server, so please test again over there, once the new version of ELViS is deployed over there.
