### ISSUE TITLE
change error message for last name on registration form

### ISSUE THREAD

**Issue by wouteraddink** [DiSSCo/ELViS#141]
#### Description

to be consistent in terms, when registering as new  user and leaving last name blank, the error message says: "Please enter a surname". This should be "Please enter your last name"

very minor issue.

**Comment by cannedit** [comment]
This has been taken care of in the ELViS version 0.6.0, released on the Acceptance server on 15/01/2021.

**Comment by B-San-Chi** [comment]
It is still written "Please enter a surname"

**Comment by cannedit** [comment]
I am sorry, but I can't reproduce this (see the screenshot attached), please check again ...
![ELViS_LastName_Surname](https://user-images.githubusercontent.com/22167327/105176948-3e7a0100-5b26-11eb-921c-8c20b312ce82.png)

**Comment by B-San-Chi** [comment]
Thank you!

----- Mensaje de Wim van Dongen <notifications@github.com> ---------
      Fecha: Wed, 20 Jan 2021 04:49:26 -0800
         De: Wim van Dongen <notifications@github.com>
Responder-A: DiSSCo/ELViS  
<reply@reply.github.com>
     Asunto: Re: [DiSSCo/ELViS] change error message for last name on  
registration form (#141)
       Para: DiSSCo/ELViS <ELViS@noreply.github.com>
         Cc: Begoña Sánchez Chillón <bego@mncn.csic.es>, Comment  
<comment@noreply.github.com>

>  
>
>   I am sorry, but I can't reproduce this (see the screenshot  
> attached), please check again ...
> [1]
>
>   —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub[2], or unsubscribe[3].

----- Terminar mensaje de Wim van Dongen <notifications@github.com> -----



Vínculos:
---------
[1]  
https://user-images.githubusercontent.com/22167327/105176948-3e7a0100-5b26-11eb-921c-8c20b312ce82.png
[2] https://github.com/DiSSCo/ELViS/issues/141#issuecomment-763584608
[3]

**Comment by B-San-Chi** [comment]
OK!!! Now is correct!!! Thanks
