### ISSUE TITLE
login with username?

### ISSUE THREAD

**Issue by wouteraddink** [DiSSCo/ELViS#142]
#### Description
the new login screen now states username or email, but we have no usernames in ELViS?

**Comment by philippeloret** [comment]
I agree with Wouter.

**Comment by cannedit** [comment]
Correct, this is standard Keycloak behaviour, we will change this.

**Comment by wolodkin** [comment]
This is still an open issue, the login screen says "Username or email". Maybe the customized theme was not activated under Configure/Realm Settings/Themes?

**Comment by emhaston** [comment]
I'm also still seeing Username or email when I log in.

**Comment by philippeloret** [comment]
Me too, I still see "Username or email" in login screen

**Comment by cannedit** [comment]
@wolodkin, @emhaston and @philippeloret: thank you for spotting this; I am sure it's indeed just a keycloak glitch and we will fix this.
