### ISSUE TITLE
Questions and Feedback

### ISSUE THREAD

**Issue by B-San-Chi** [DiSSCo/ELViS#143]
#### Description
fill in the different sections and an error occurs when sending it

#### Steps to reproduce the issue

1.  Open the section Questions and Feedback
2. Write the text in the field Subject an the explanation in the field comments o question
3. Press the button Submit

#### What's the expected result?

-Send the message

#### What's the actual result?

- None. Error message appears: 
"Something went wrong uploading the form, please try again"

#### Additional details / screenshot

![imagen](https://user-images.githubusercontent.com/58851483/100999157-acf60600-355c-11eb-9fbc-2315d26e61a0.png)

**Comment by B-San-Chi** [comment]
![imagen](https://user-images.githubusercontent.com/58851483/101000207-d82d2500-355d-11eb-833c-98ba8ade972b.png)

**Comment by RBGE-Herbarium** [comment]
I also got this message

![image](https://user-images.githubusercontent.com/63307210/101472290-56177480-3940-11eb-9b14-774e2eecf283.png)

**Comment by cannedit** [comment]
We have solved this, so please test again.

**Comment by mtrekels** [comment]
Still an error message, but a 500 message now

![image](https://user-images.githubusercontent.com/52746754/102763373-d941bd00-4379-11eb-9676-e254c938c792.png)

**Comment by mmarschler** [comment]
I get an error 500 message too when submitting the feedback.

**Comment by cannedit** [comment]
This has been fixed and can now be tested again.

**Comment by mmarschler** [comment]
Submitting the question/feedback worked well (see screenshot), but I haven't received an email.

![ELViS_question_feedback_04-01-2021](https://user-images.githubusercontent.com/75616869/103542458-40449300-4e9d-11eb-9e9d-dcf9fa086048.JPG)

**Comment by B-San-Chi** [comment]
OK. it already works correctly, at least the message indicates that the question has been sent
