### ISSUE TITLE
Navigation between institutions and facilities (minor issue)

### ISSUE THREAD

**Issue by philippeloret** [DiSSCo/ELViS#145]
#### Description

As a requester, I would like to know what are the facilities of 'Agentschap Plantentuin Meise' institution. I choose the 'facility#1' but I cannot go back to the institution to see others facilities without using 'previous' button of my browser. In the facility sheet, there is no link to the institution and the breadcumb cannot be used to go back to the institution. 

May be, we can add a link to the institution or modify the breadcrumb ?

It is a minor issue of course but may be we can improve the user experience and it could be interesting to user to have information about the institution in the facility sheet.

#### Steps to reproduce the issue

1.  Click on 'Institutions' menu
2.  Click on 'Agentschap Plantentuin Meise'
3.  Click on 'Facilitles' tab
4. Click on 'facility#1' facility

**Comment by cannedit** [comment]
I think it's best to adapt the breadcrumb, we will do that in due time; btw: by using the back-button of the browser a user can still go back to the institution.

**Comment by cannedit** [comment]
This has been taken care of, please test.

**Comment by jgrieb** [comment]
Tested - there are now 2 breadcrumb items when looking at one facility: 
1 brings the user back to see the overview of all facilities
1 brings the user back to see the other facilities of the institution where the previously selected facility belongs to

Looks good to me
