### ISSUE TITLE
An internal server error (dialog box) occurred when I submitted for the first time my requests as a requester.

### ISSUE THREAD

**Issue by lisasund** [DiSSCo/ELViS#147]
An internal server error (dialog box) occurred when I submitted for the first time my requests as a requester. It seems that requests were actually submitted. The requests were 'This is a test' and 'This is another test'.

_Originally posted by @philippeloret in https://github.com/DiSSCo/ELViS/issues/136#issuecomment-737268838_

Same issue  reported by 2 other users in https://github.com/DiSSCo/ELViS/issues/136

**Comment by RBGE-Herbarium** [comment]
I also got this error (Error 500)

![image](https://user-images.githubusercontent.com/63307210/101465210-90c8df00-3937-11eb-8dab-942361f9688c.png)

**Comment by cannedit** [comment]
This is indeed a bug, we will take care of it.

**Comment by cannedit** [comment]
We have solved this, so please test again.

**Comment by mtrekels** [comment]
Not ok: see https://github.com/DiSSCo/ELViS/issues/136#issuecomment-748876998

**Comment by mmarschler** [comment]
I just tried it, same error (Error 500).

**Comment by cannedit** [comment]
This has been fixed and can now be tested again.

**Comment by mmarschler** [comment]
Everything is fine now! The request has been submitted without error.

**Comment by philippeloret** [comment]
I made another test and it seems fine now.

**Comment by B-San-Chi** [comment]
It's solved.
