### ISSUE TITLE
VA Request - Licensing options

### ISSUE THREAD

**Issue by RBGE-Herbarium** [DiSSCo/ELViS#149]
#### Description

Currently the licensing options are two checkboxes and the user can only select one at a time. However, for digitisaton, many institutes have different licences for the data and images, eg CC0 for data and CC-BY for images. There may also be different licences for different collections, particularly the library & archive collections if they are to be included in the future.

#### Steps to reproduce the issue

1.  Create new request
2.  Add institute, Data Storage & Release
3.  Licence type is below with two options

#### What's the expected result?

- Wanted to select different licences for data and images

#### What's the actual result?

- Could only select either option (not both).

#### Additional details / screenshot

![image](https://user-images.githubusercontent.com/63307210/101464643-ce793800-3936-11eb-9c40-6dca1430fa8c.png)

**Comment by wouteraddink** [comment]
This worked as agreed upon. For digitisation data created with Synthesys+ funding only these  licenses are allowed.
