### ISSUE TITLE
Login only possible by selecting login button

### ISSUE THREAD

**Issue by mtrekels** [DiSSCo/ELViS#15]
#### Description

This is rather an unexpected behavior than a bug.

Using a webbrowser: when entering your credentials, pressing 'enter' will not perform the login. You need a mouse click on the 'login' button or an extra 'tab' to select the login button.

#### Steps to reproduce the issue

1.  Enter credentials
2.  Press enter without changing to the login button
3. 

#### What's the expected result?

- The exected behavior was that after entering my pwd, hitting 'enter' would bring me in the system

#### What's the actual result?

- I had to click the button or press 'tab' first

**Comment by cannedit** [comment]
this ticket is added in Redmine as issue #46717
https://code.pictura-dp.nl/issues/46717
