### ISSUE TITLE
VA Call - download request not possible as requester

### ISSUE THREAD

**Issue by RBGE-Herbarium** [DiSSCo/ELViS#151]
#### Description

In Requests section, I'm not able to download a request when logged in as a Requester.
https://elvis-accept.pictura-hosting.nl/requests

#### Steps to reproduce the issue

1.  
2. 
3. 

#### What's the expected result?

-

#### What's the actual result?

- Download button is greyed out.

#### Additional details / screenshot

![image](https://user-images.githubusercontent.com/63307210/101471104-cae9af00-393e-11eb-8ea7-1a7d99474f94.png)

**Comment by cannedit** [comment]
The download a request functionality is only available after a request has been approved.
