### ISSUE TITLE
VA Call - Institutions involved: Collections & Preservation type to be a dropdown?

### ISSUE THREAD

**Issue by RBGE-Herbarium** [DiSSCo/ELViS#152]
#### Description

When entering an Institution, we are asked to enter a Collection. At present this is a free text field. Will this become a dropdown list when the Collections data have been entered?

Will Preservation type also be a dropdown list?

#### Steps to reproduce the issue

1.  Create new request
2.  Select an institution
3.  Collection and Preservation Type fields are visible in first section

#### What's the expected result?

- To be able to select from a dropdown list

#### What's the actual result?

- Box is a free text field

#### Additional details / screenshot

![image](https://user-images.githubusercontent.com/63307210/101474390-025a5a80-3943-11eb-9ee5-04ccf4993588.png)

**Comment by cannedit** [comment]
Answer to your first question ("Will this become a dropdown list when the Collections data have been entered?"): yes, that's the idea.

Answer to your second question ("Will Preservation type also be a dropdown list?"): no, that's not envisaged for now, unless the community can come up with a general list of preservation types applicable for all kinds of collections.
