### ISSUE TITLE
VA call text

### ISSUE THREAD

**Issue by wouteraddink** [DiSSCo/ELViS#16]
#### Description
The description for the first VA call is published here: https://www.synthesys.info/access/virtual-access.html
It would be good to have the text also in the system under the calls tab

**Comment by cannedit** [comment]
this information is addded to the already existing Redmine issue #44974
https://code.pictura-dp.nl/issues/44974

**Comment by Karin-Wiltschke** [comment]
please correct
http://elvis-accept.pictura-hosting.nl/calls/7d4cc4af-ac72-406e-b128-0edb23e48659
9 Partners to 19 Partners (entrance sentence)

**Comment by cannedit** [comment]
will be corrected, is Redmine ticket: https://code.pictura-dp.nl/issues/47486
