### ISSUE TITLE
modify the information about my institution

### ISSUE THREAD

**Issue by B-San-Chi** [DiSSCo/ELViS#161]
#### Description
If my institution is involved in a project, who can modify its information if necessary, only the requester? can the VA just notify the requester, not modify anything? I am working with the test project made by Requester Picturae

#### Steps to reproduce the issue

1.  
2. 
3. 

#### What's the expected result?

-

#### What's the actual result?

-

**Comment by cannedit** [comment]
Yes, for now the Requester is the only person to modify a Request, so a TA and VA Coordinator have to get in touch with the Requester (via the comments section) to get things changed if needed.

**Comment by B-San-Chi** [comment]
Ok. Thanks
