### ISSUE TITLE
Visibility of Draft-status for coordinators

### ISSUE THREAD

**Issue by mmarschler** [DiSSCo/ELViS#163]
To my knowledge, it is planned to make the "Draft"-status requests only visible for admins and the original requesters.

But for us VA/TA coordinators, it is also very important to see drafts. In my experience, questions arise when the requesters fill in the form, and they usually contact the coordinator (not the administrator) to help. So it is essential for us to have the possibility to look at it.

**Comment by cannedit** [comment]
Sorry, this setup was already decided some time ago and in practice there is plenty of time to communicate back and forth between Requester and Coordinators once a Request is submitted. FYI: submitted is just a preliminary status for a Request, so most of the parts of the Request can still be changed (by the Requester) in this stage. So I hope for now we can stick with the current situation?

**Comment by wouteraddink** [comment]
Works as intended, as Wim explained submitted is just a preliminary status here.
