### ISSUE TITLE
Information about real time storage in TA requests

### ISSUE THREAD

**Issue by mmarschler** [DiSSCo/ELViS#164]
In VA requests, requesters can see an information about real time storage in the upper right corner (blue box). I suggest to include this info box in TA requests too.

**Comment by mmarschler** [comment]
Just saw that this is already on the agenda.

**Comment by cannedit** [comment]
This is already taken care of and will be available in the next Acceptance server deployment.

**Comment by cannedit** [comment]
This is now available, please test.

**Comment by mmarschler** [comment]
The blue box can be seen, thx.
See also comment in issue #165
