### ISSUE TITLE
TA: Proposed length of visit/start date/end date

### ISSUE THREAD

**Issue by mmarschler** [DiSSCo/ELViS#166]
The information in the field "Proposed length of visit" says that the "visit length must match the number of working days...". 
When the number proposed length of visit doesn't match the start/end date, there is no error message. So I can apply for, e. g. 10 working days with a start date 1.2. and end date 2.2.

Furthermore, the wording should be improved. In our experience from former TA calls, there is a lot of confusion about these fields - requesters fill in these fields heterogenously as they understand the meaning of these fields differently. And many requesters do not know that they can arrive a day before the work starts. So we suggest following improvements:

Proposed length of visit -> Proposed length of visit (number of working days)
Proposed start date -> Proposed start date (arrival date, usually one day before the first working day)
Proposed end date -> Proposed end date (departure date, usually one day after the last working day)

**Comment by scottwilson-nhm** [comment]
I had the same response to this issue; the platform should be able to calculate if the days requested matches the day range chosen. 

Wording wise, I can produce better wording as this has caused confusion before!

**Comment by cannedit** [comment]
I will check with the team whether we can squeeze in the calculation,, but - as stated before - the deadline is approaching fast and there's still so much to take care of. 
As for the wording of the text: I have asked several times for the proper texts for the TA Request form and finally there were some (not even all of them till now) were provided, among which the one currently shown for this functionality. We can change it of course, but please provide the right wording a.s.a.p. and try to avoid asking us to do this over and over again.

**Comment by wouteraddink** [comment]
the proposed wording could be added through i-info icons: 
Proposed start date -> arrival date, usually one day before the first working day
Proposed end date -> departure date, usually one day after the last working day

**Comment by mmarschler** [comment]
The function works now. I can choose start and end date and the proposed length of visit only allows me to select the number of working days that are possible between start and end.
