### ISSUE TITLE
Search for requester & request

### ISSUE THREAD

**Issue by mmarschler** [DiSSCo/ELViS#167]
#### Description
Now it is not possible to search for all requests from one requester - a function that is essential for TA/VA coordinators. You can either search for the requester in the requeesters-tab or search for a request in the requests-tab, but you cannot search for both informations at once.
Is it possible to include the requester name in the text search within the request tab? So that all requests from one requester can be filtered.

**Comment by cannedit** [comment]
I will write this down as an extra feature, not sure whether we can take care of this before the 1st of March deadline, because there are still many many things to do.

**Comment by LarissaS** [comment]
As a requester I can see all other requesters and their requests, is it a normal practice?

**Comment by cannedit** [comment]
Searching on (part of) email addresses, so requesters, is not also available, please test.

**Comment by LarissaS** [comment]
it works fine, but I noticed that when I search for "be", I get on top of a list two requesters, whose names or emails do not contain any "be":
Anne Koivunen | anne.koivunen@helsinki.fi | - |  
AL | Anton Lakotka | a.lakotka@picturae.com | 0012-7129-8628-4523 |  

And when I search for "de", Anne Koivunen is still on the top of a list without any "de" in her record. Bug?

**Comment by emhaston** [comment]
I believe that the comment above is caused by the letters "de" appearing in the word Moderator in Anne's record. The searching works for me.

The question now is whether text in the User Groups field is included in the search.

**Comment by philippeloret** [comment]
It works fine. We can search by keyword or email.

As seen above, maybe too much information are included in the search. We can searh for example "moderator" and see the list of all institution moderator.

**Comment by cannedit** [comment]
Hi @emhaston,
Yes, that's correct.

Hi @philippeloret,
Sorry, I don't see any problem with this; I think this functionality is now working fine and can lead to a creative use of it, so suits multiple purposes.

**Comment by philippeloret** [comment]
Hi @cannedit, This is not a problem, just a comment to explain that we could use this functionality to search requester in another way. This works fine.
