### ISSUE TITLE
Search for institutions - country

### ISSUE THREAD

**Issue by mmarschler** [DiSSCo/ELViS#169]
Now the search for institutions only includes GRID-Id & the institution name. Search for countries and towns would be desireable. Maybe by implementing a full-text search?

**Comment by cannedit** [comment]
See my remarks in Github issue #97.

**Comment by LarissaS** [comment]
Without searching by country it's impossible to find all three Belgian institutions (RBINS, RMCA, BGM). RMCA uses its French name (Musee Royal de L'Afrique Centrale), RBINS- English, but Brussels is written in French - Bruxelles. If I search for "Royal" I find both museums but not Meise. If we add a city name to the title it will not help, may be we should add "Tervuren, Belgium", "Brussels, Belgium", "Meise, Belgium".

**Comment by cannedit** [comment]
We are aware of this and we will take care of it later; for now it's only 20 institutions on 2 pages, so not such a big deal yet.

**Comment by cannedit** [comment]
Searching for cities and countries is now available, please test.

**Comment by emhaston** [comment]
Tested and it works for me. I was going to search for Netherlands and Holland to see how it manages a search for people who are not sure of the correct country name but Naturalis is not in.

**Comment by jgrieb** [comment]
Tested for several cities and countries and generally it works well. The search term must be exactly the same as the data is in the system (e.g. 'Jardin Botanico' does not work, only 'Jardín Botánico' does, or 'Brussels' does not work only 'Bruxelles' does) but I think that's okay. The search even works when searching for the name of the institution coordinator or the address.

**Comment by philippeloret** [comment]
It works fine. As seen above, the search terl must be exact and users have to take care about the accents (on characters). You cannot find 'Jardín Botánico' with 'jardin' because of the accent.

**Comment by cannedit** [comment]
Hi @philippeloret,
Thank you and the character issue is already dealt with, so will be solved with the next deployment.

**Comment by cannedit** [comment]
Hi @philippeloret,
Thank you, I will make sure this will be corrected.
