### ISSUE TITLE
VA coordinators and institutes

### ISSUE THREAD

**Issue by wouteraddink** [DiSSCo/ELViS#17]
#### Description

an updated list of  VA coordinators and their institute GRID IDs can be found here:
https://docs.google.com/spreadsheets/d/1xRZU5OMvyzX57-H4_nps5dngtSuC2Uuu1V-QMUiiV1Q

This data can be imported. Additional metadata for the institutes can be retrieved from GRID data which can be downloaded here: https://www.grid.ac/

A connection can also be made to WikiData for additional (unvalidated) data about the institutes and to CETAF for validated data. A download file with CETAF passport data is available for import.

**Comment by cannedit** [comment]
this information is addded to the already existing Redmine issue #46589
https://code.pictura-dp.nl/issues/46589

**Comment by HMHardy** [comment]
It's not clear why the organisations appear in the order that they do (in the Institutions tab)? Maybe alphabetic or some other obvious organising principle would be helpful? (although the same issue applies to the Synthesys website list :) )

**Comment by cannedit** [comment]
We will put them in alphabetical order by name
Registered as Redmine issue: 47504
https://code.pictura-dp.nl/issues/47504
