### ISSUE TITLE
TA Project acronym

### ISSUE THREAD

**Issue by mmarschler** [DiSSCo/ELViS#171]
In the section "Other institutions", the last field asks for "request number(s)". In former TA calls, it was called "project acronym". Please adapt this.

When/where will this project acronym be created? Where will it be found in ELViS? Will it be listed in the requests tab?

**Comment by cannedit** [comment]
As indicated during the last Synthesys+ WP6 meeting we have to gradually switch from 'old' Synthesys tool terminology to 'new' ELViS terminology, so in ELViS terminology this is a Request, so hence "Request number". These numbers are not visible yet, but ofc each Request has a number, a unique identifier, so we should indeed make this visible somewhere to enable Requesters to fetch and use these.

Btw: in the new version of the TA Call Request form, we already changed "Project" into "Request" as shown during the Synthesys+ WP6 meeting on the 26th of January 2021, but not everywhere, only where it's applicable (for example a Request is a part of a Project, hence we didn't change "Project methodology" into "Request methodology". I understand this might be confusing for people switching from one tool to the other, but that's just a matter of proper communication about this.

**Comment by cannedit** [comment]
All texts provided anew have been updated, so please test.

**Comment by mmarschler** [comment]
All texts are fine now and the i-icon-texts and character counts make it very clear and userfriendly. Thanks everybody!
