### ISSUE TITLE
TA: Project discipline - drop down

### ISSUE THREAD

**Issue by mmarschler** [DiSSCo/ELViS#173]
Currently, the fields "project discipline" and "Project specific discipline" are a text fields. In the old Synthesys-platform, they used to be drop down lists. Categories would be easier to evaluate.

**Comment by cannedit** [comment]
I will see whether we can squeeze them in, but please provide me the values for those two dropdown lists (I have asked for this already a while ago, but I still haven't received them to my knowledge).

**Comment by cannedit** [comment]
This is fixed now, so please test.

**Comment by mmarschler** [comment]
Tested, it works well!

**Comment by philippeloret** [comment]
It's ok for me.
