### ISSUE TITLE
Admin function: Blank page when clicking TA request

### ISSUE THREAD

**Issue by sharifX** [DiSSCo/ELViS#174]
#### Description
When I am logged in as ELViS administrator, I can see the list of all the requests. However, clicking the TA requests shows a blank page. 

#### Steps to reproduce the issue

1.  Login as Admin
2. Go to requests
3. Click on one of the Transnational Access requests

#### What's the expected result?

Expected to see the full details of the result. 

#### What's the actual result?

Blank page. The URL seems to be not going to /calls/unique-id
This does not have for the VA requests.

**Comment by scottwilson-nhm** [comment]
Also confirming that I encounter this issue too.

**Comment by cannedit** [comment]
This is already taken care of, so will be fixed in the next Acceptance server deployment.
