### ISSUE TITLE
Use-case of shared VA/TA coordinator role not covered

### ISSUE THREAD

**Issue by mtrekels** [DiSSCo/ELViS#175]
#### Description
This issue is a reminder that the use-case for multiple people within an institute can take up the role as a VA/TA coordinator is not (yet) covered.

More specifically when a shared general email address is used for the VA/TA coordinator. At the registration, there is a one email for one person connection (e.g. a name and ORCiD have to be provided).

The underlying reason is to provide continuity for requesters, such that internal (re-)organization of the institute has no (visible) impact.

#### Additional details

Work-around exists: names can be changed in the system

**Comment by mmarschler** [comment]
This would be a very important function for NHMW too, as (at least!) two people (Andrea Stadlmayr as TA coordinator, me as VA coordinator) work with our general email address (synthesys@nhm-wien.ac.at). Now it is only possible to give the TA coordinator role to Andrea's email address, but all TA emails should go to synthesys@nhm-wien.ac.at.

**Comment by cannedit** [comment]
This has been taken care of, please test.

**Comment by mtrekels** [comment]
The assignment of roles (as an institution moderator, can't test as an admin), works fine!

It doesn't solve the use-case of an institutional email address (i.e. the case of 1 email linked to several people, now it's still a 1person-1email relationship). However, this can be solved at the institutional level, and can be solved by changing internal processes.

OK to close from my point of view, what do you think @mmarschler  ?

**Comment by mmarschler** [comment]
Hi Maarten, yes, it's ok for me to close this issue. 
We solved this problem by changing the name of this account: First name: Synthesys+ Team, Last name: NHM Vienna. 
Best, M.
