### ISSUE TITLE
No confirmation email received after registration

### ISSUE THREAD

**Issue by LarissaS** [DiSSCo/ELViS#176]
#### Description

I have successfully registered as the requester. But I have not received a confirmation email. I can enter the site.

#### Steps to reproduce the issue

1.  
2. 
3. 

#### What's the expected result?

-

#### What's the actual result?

-

**Comment by philippeloret** [comment]
I've tested the registration with the same result. I registered a new user successfully but I didn't receive confirmation email. But I can login and enter the site.

**Comment by cannedit** [comment]
Unfortunately this is still the case on our Acceptance server. However, this will not occur on the Production server. So, I hereby close this issue and ask you kindly to check on the Production server once that is updated later this week.
