### ISSUE TITLE
Edit my profile issue

### ISSUE THREAD

**Issue by philippeloret** [DiSSCo/ELViS#177]
#### Description
I edit my profile to change personal information (birth date and institution).

#### Steps to reproduce the issue

1. Go to my profile
2. Edit my profile and change birth date and save. My profile was updated.
3. Go to institution tab
4. Go to my profile again
5. See any change in my profile. New information are not visible.
6. Log off
7. Log in again
8. My profile is updated now.

#### What's the expected result?
I expect to see my updated profile.

#### What's the actual result?
When I updated my profile, I saw new available information. But if navigate into the site (go to institution tab) and I come back to my profile, updated information are not visible (only previous information are shown). I log off and log in again, I could see my profile updated as expected.

**Comment by mmarschler** [comment]
Same here... but you don't have to log-in and log-out necessarily, changes of the profile can be seen also after refreshing the browser window.

**Comment by cannedit** [comment]
Hi @philippeloret and @mmarschler,
Yes, I noticed that too, but I guess logging out and logging in again in case of changing of profile/roles changes is not a big problem right? I will see whether we can solve this, otherwise it's something I will mention in the manual.

**Comment by philippeloret** [comment]
I think this can be confusing for the user. When you change your profile, you expect to see updated information at any time. Moreover, you cannot see your profile in the people tab (institution page) if you changed your "institution". If we need to refresh our browser or logout, I has to be mentioned.

**Comment by cannedit** [comment]
We are looking into this at the moment and in case we can't solve it, I will make sure it will be mentioned in the manual.

**Comment by cannedit** [comment]
This is fixed now, please test.

**Comment by mmarschler** [comment]
Tested, it's ok now!

**Comment by philippeloret** [comment]
It works fine now.
