### ISSUE TITLE
draft request is missing

### ISSUE THREAD

**Issue by LarissaS** [DiSSCo/ELViS#178]
#### Description
Last week (Friday?) I created a new request with the title "Study of bonobo..." I think. Today I could not find it back. Not in my requests and not by searching. 

#### Steps to reproduce the issue

1.  
2. 
3. 

#### What's the expected result?

-

#### What's the actual result?

-

**Comment by cannedit** [comment]
Hi @LarissaS,
This is probably due to the fact that we had several attempts to deploy the latest ELViS version on the Acceptance server from Friday till Monday, so please try to reproduce this again (my guess is that it will not happen again) :-).
