### ISSUE TITLE
Password error behaviour

### ISSUE THREAD

**Issue by AnniinaK** [DiSSCo/ELViS#18]
#### Description
Leave the password fields empty in the registration, you will get an error message saying "Please enter a valid password" and "Passwords have to match". When starting to type a password, the error messages and red highlights stay, even if the passwords match. Error is cleared only after clicking register again. Maybe confusing (for example one may think the passwords do not match even if they do) but perhaps minor issue?

#### Steps to reproduce the issue

1.  Fill in other fields for registration, leave password empty
2. Click register
3. Start typing a password

#### What's the expected result?

- When starting to type a password, the error messages should be cleared

#### What's the actual result?

- The error messages remain until you click register again

**Comment by cannedit** [comment]
this ticket is added in Redmine as issue #46705
https://code.pictura-dp.nl/issues/46705
