### ISSUE TITLE
typographical issue on "Affiliated addressess" (institution)

### ISSUE THREAD

**Issue by philippeloret** [DiSSCo/ELViS#180]
#### Description
There is a typographical error on the institution page ("Affiliated addressess") : Too much "s".

Example with Agentschap Plantentuin Meise :

https://elvis-accept.pictura-hosting.nl/institutions/grid.425433.7

![Capture du 2021-02-04 11-00-50](https://user-images.githubusercontent.com/75371870/106876910-811c0b80-66d8-11eb-803c-026192c65bbe.png)

**Comment by cannedit** [comment]
This is fixed now, please test.

**Comment by mmarschler** [comment]
Tested, ok now.
