### ISSUE TITLE
layout distortion

### ISSUE THREAD

**Issue by LarissaS** [DiSSCo/ELViS#183]
#### Description
As an institutional moderator I'm checking a submitted request. There are distortions and overlaps in layout in some parts of the request: project information, resources needed/general, supporter information.

#### Steps to reproduce the issue

1.  Log in as administrator
2.  search for requests -> only for my institution
3. open request

https://elvis-accept.pictura-hosting.nl/requests/ta/f08b46a0-b79c-467c-93ac-357e06e75efd

#### What's the expected result?

-

#### What's the actual result?

-

**Comment by cannedit** [comment]
Can you please provide some more information: which browser/version are you using, does it occur also in other browsers/version and can you please provide a screenshot?

**Comment by LarissaS** [comment]
Sorry, the steps were not right! 
Steps to reproduce the issue:
- Log in as administrator
- search for requests -> search on "Bonobo", you will get two requests, choose "New study of bonobos" (because there are more information in the fields.
- open request
-In some fields you see distortion (see screenshots for Microsoft Edge 2020 and Google Chrome ):
Microsoft Edge:
![image](https://user-images.githubusercontent.com/949726/107365780-92e91e80-6add-11eb-9091-c1af2c03f2f6.png)
![image](https://user-images.githubusercontent.com/949726/107365854-a98f7580-6add-11eb-9092-08d281322292.png)
![image](https://user-images.githubusercontent.com/949726/107365876-b0b68380-6add-11eb-97d1-560aa2506060.png)

Google Chrome:
![image](https://user-images.githubusercontent.com/949726/107365911-bd3adc00-6add-11eb-9dd0-1c5d8bf3600f.png)
![image](https://user-images.githubusercontent.com/949726/107365926-c6c44400-6add-11eb-8dd4-0aca93ddb321.png)
![image](https://user-images.githubusercontent.com/949726/107365939-ccba2500-6add-11eb-8541-6a0d36c01cc4.png)

It is the same for other requests, see for example "This is my modified test request" (In Google Chrome):
![image](https://user-images.githubusercontent.com/949726/107366145-1440b100-6ade-11eb-9659-6cd2adb0d741.png)
![image](https://user-images.githubusercontent.com/949726/107366182-1e62af80-6ade-11eb-8f46-c8e224b18f0f.png)

**Comment by cannedit** [comment]
This is fixed now, please test.

**Comment by LarissaS** [comment]
In order
