### ISSUE TITLE
Invalid value in "email" field breaks the UI

### ISSUE THREAD

**Issue by vixriihi** [DiSSCo/ELViS#19]
#### Description
When on miss typing email in login box the error message breaks the UI

#### Steps to reproduce the issue

1. Type "as" to "Email"-field on top right (anything that's not valid email will do)
2. Blur the field by clicking anywhere on the page outside of the email field

#### What's the expected result?

- Error message that doesn't break the UI

#### What's the actual result?

-"Email" field is raised or on mobile not visible

#### Additional details / screenshot
Desktop:
![image](https://user-images.githubusercontent.com/5203261/71891954-6f240e00-3150-11ea-86fa-4ff193772bb3.png)
Mobile:
![image](https://user-images.githubusercontent.com/5203261/71891994-86fb9200-3150-11ea-919f-88566a177ffb.png)

**Comment by cannedit** [comment]
this ticket is added in Redmine as issue #46706
https://code.pictura-dp.nl/issues/46706
