### ISSUE TITLE
TA: Text update request

### ISSUE THREAD

**Issue by mmarschler** [DiSSCo/ELViS#190]
#### Description
If I change my submitted request, there is a info-text at the bottom of the page that is VA-specific. This text has to be adapted to TA.

![ELViS_request_update_2021-02-08](https://user-images.githubusercontent.com/75616869/107226892-fd855600-6a1a-11eb-8599-7b9f45659132.PNG)

**Comment by cannedit** [comment]
We will adapt this.

**Comment by cannedit** [comment]
Will it be Ok to just change these parts of the text shown above:

- VA Coordinators = TA Coordinators (twice)
- peer review = scoring

**Comment by mmarschler** [comment]
No, there are some more changes.
@scottwilson-nhm : Could you please provide an adapted text for this? Thx in advance!

**Comment by cannedit** [comment]
Ok, but for now I have asked to already put in the suggested adaptions, because we're in the middle of a huge overhaul of all text changes and we can't continue doing this over an over again, sorry. So please provide any additional changes a.s.a.p.

**Comment by cannedit** [comment]
See Github issue #196
