### ISSUE TITLE
Links in description of instruments or servicesn (minor issue)

### ISSUE THREAD

**Issue by mmarschler** [DiSSCo/ELViS#191]
#### Description
Links that are given in the description of instruments or services are shown as text

#### Steps to reproduce the issue
1.  select your institution
2. create or edit a facility and add a description of instruments or services including a link
2. go to tab "facilities"
3. the link in the description is embedded as text

#### What's the expected result?
- a link that works (like the Url to the website of the facility)

![ELViS_instruments_list_2021-02-08](https://user-images.githubusercontent.com/75616869/107236930-7d64ed80-6a26-11eb-8a67-35c23959d982.PNG)

**Comment by cannedit** [comment]
We will take care of this.

**Comment by cannedit** [comment]
This is fixed now, please test.

**Comment by LarissaS** [comment]
Not solved, link in "Instruments" is not clickable.

**Comment by cannedit** [comment]
Please try again, because according to the attached video it is working ...

https://user-images.githubusercontent.com/22167327/108331419-08847700-71cf-11eb-9c95-bdf849e588bb.mp4

**Comment by LarissaS** [comment]
Yes, for Wien it works, but my link is not clickable:
![image](https://user-images.githubusercontent.com/949726/108334468-43d47500-71d2-11eb-99ff-bc411c931ee0.png)

**Comment by mmarschler** [comment]
Yes, it works well for our institution.

@LarissaS : You have given the link in the name-field of the instrument/service. I think this is just a text field. I put our links in the description field!
