### ISSUE TITLE
TA: Layout of request (minor issue)

### ISSUE THREAD

**Issue by mmarschler** [DiSSCo/ELViS#192]
#### Description
The layout of requests needs adaption: there is not enough space between of the catagory names and the information of the fields, in several cases category name and field overlap. 

#### Steps to reproduce the issue
1.  log in as TA coordinator
2. got to request and select a request

![ELViS_layout_request_2021-02-08](https://user-images.githubusercontent.com/75616869/107237559-2875a700-6a27-11eb-841b-d44f4b5f2624.PNG)

**Comment by cannedit** [comment]
We will look into this. Does this have something to do with the screen width/browser?

**Comment by mmarschler** [comment]
I don't think so. We have tried it with 4 different computers/screens and with different zooms - it stays the same.

**Comment by cannedit** [comment]
Please provide the link to the request.

**Comment by mmarschler** [comment]
Here are two examples:
https://elvis-accept.pictura-hosting.nl/requests/ta/a1552bd7-e8d9-48ae-a347-7e167f65f703
https://elvis-accept.pictura-hosting.nl/requests/ta/4dd6b7c7-0f25-4a4a-b8ee-cf70e90a3f72

**Comment by cannedit** [comment]
Ok, thanks, we will look into this; it seems that there just isn't enough space between the labels and the values of the text fields; this should not be too difficult to solve I think.

**Comment by cannedit** [comment]
This should be fixed now, please test.

**Comment by LarissaS** [comment]
It looks fine now.
