### ISSUE TITLE
TA: add other researchers

### ISSUE THREAD

**Issue by mmarschler** [DiSSCo/ELViS#193]
#### Description
In the section "Researchers team details" you can only add "other researcher(s) of your group" by selecting a name from the dropdown-list (i. e. registered users). Although you can fill names of other people who are not listed/registered, this information is not stored.

#### Steps to reproduce the issue
1.  create a TA request
2. fill in a name in "other researcher(s) of your group" that is not listed in the dropdown-list
3. save your request
4. check your request again -> the name has vanished

#### What's the expected result?
- Other names, that are not listed in the dropdown-list, shall be safed too (especially because in practice not all research team members of all TA requesters will be registered on ELViS).

filling out a name that is not listed is possible:
![ELViS_research_team_2021-02-08](https://user-images.githubusercontent.com/75616869/107241648-78566d00-6a2b-11eb-9d71-7ed12fa5caba.PNG)

but it is not saved:
![ELViS_research_team2_2021-02-08](https://user-images.githubusercontent.com/75616869/107241716-899f7980-6a2b-11eb-82d3-78873e57c9da.PNG)

**Comment by cannedit** [comment]
The original idea was that in case a requester would like to add other requesters to his/her team, then he/she should make them aware of the fact that they have to register first. This would be the first step for getting those extra team members also involved in filling in/completing the TA form, which we intended to implement in the second ELViS development phase.
But as requested by Wouter in this morning's WP6 Zoom session (09/02), we will go back to the original 'old fashioned' way of enabling the requester to put the name of his/her team members in a plain text field, just like it is done at the moment for the VA form.

**Comment by cannedit** [comment]
It's now possible to add any other user, which is not yet registered in ELViS yet, by typing his/her name in the text field and clicking on the "enter"-key.

**Comment by mmarschler** [comment]
Great! Works well now. Thx Wim.
