### ISSUE TITLE
Text below submitted request to be updated

### ISSUE THREAD

**Issue by LarissaS** [DiSSCo/ELViS#196]
#### Description

requester can still open submitted request with 'to be evaluated" status and update an information. The in text below it's written "VA coordinator" instead of "TA coordinator" (see screenshot)

#### Steps to reproduce the issue

1.  Open in My request 'to be evaluated" request
2. go to the end of the proposal
3. Under "Is your request ready to be updated?" you will see the text for VA call 

#### What's the expected result?
TA coordinator as we are in TA request
-

#### What's the actual result?

-
![image](https://user-images.githubusercontent.com/949726/107765613-7691ef80-6d32-11eb-94d9-ef811c188b4b.png)

**Comment by LarissaS** [comment]
It is updated, but change "digitising institutes" to "host institutes".

**Comment by cannedit** [comment]
This has been taken care of, please test.

**Comment by cannedit** [comment]
See Github issue #190

**Comment by LarissaS** [comment]
"Digitizing institute" is not updated, it has to be 'host institutes"

In general I find it not clear for a requester:
- when he is in draft version, he gets to see this text at the end of the application "Ready to submit your Transnational Access request?"

![image](https://user-images.githubusercontent.com/949726/110472254-7260b400-80dd-11eb-8394-64681caa149c.png)

after he submitted the application he still can edit it and at the end he  sees the text "Is your request ready to be updated?
If you have corrected and/or completed your request according to the instructions of the TA coordinators as provided via their comments, you can submit your changed request for approval again via the “Update request”-button. This is NOT yet the final submission. The final Submission will be dealt with via scoring after all TA coordinators from the digitising institutes involved have approved your request."
![image](https://user-images.githubusercontent.com/949726/110473417-c91abd80-80de-11eb-82d9-74d24e082426.png)

I think it has to be clear BEFORE  first submission that this is not yet final submission, but submission for approval by TA coordinator !
So, may be we could put a similar text, something like ""Is your request ready to be submitted?
This is NOT yet the final submission.  Your request has to be approved by TA coordinator. You still can update your request according to his/her comments. The final Submission will be dealt with via scoring after all TA coordinators from the digitising institutes involved have approved your request."
The last phrase is also odd! It's not a submission which will be dealt via scoring. Shell I write Krissie to look into it?



-

**Comment by cannedit** [comment]
@LarissaS we will take care of changing the "Digitizing institutes" into "Host institutes" as part of the minor issues still to be taken care of; as for any further text changes, if really necessary we need to receive them asap, but actually we don't have time anymore to discuss text changes back and forth, and we already did a thorough overhaul of all texts based on input from Krissie and Scott a few weeks ago.

**Comment by LarissaS** [comment]
Fine for me!

**Comment by cannedit** [comment]
We have changed the text now, see the screenshot attached, please test again.
![ELViS_Acceptance_NewUpdateRequestText](https://user-images.githubusercontent.com/22167327/110594602-4e54af80-817d-11eb-9fd5-91a9daf5370c.png)
