### ISSUE TITLE
information in "General " part of "Resource needs" is not saved

### ISSUE THREAD

**Issue by LarissaS** [DiSSCo/ELViS#197]
Description:
After checking my request "Test bonobo" I found out that information I put in Resources needs in general part are missing, after updating - the same. 
I checked it again with a new request (test_bonobo_again) under the new username (private email, not institutional), and result is the same, changes in other parts are saved, in "general" - not!

1.  add new request
2. fill in the fields (including General part in Resource needs)
3. submit
4. go back to My requests
5. push on button "to be evaluated"
6. no information in General part
7. type again
8. push "update request"
9. check again - no information in this part!

#### What's the expected result?

-
![image](https://user-images.githubusercontent.com/949726/108068522-7b241400-7062-11eb-9597-f59a4beefbc3.png)

#### What's the actual result?
![image](https://user-images.githubusercontent.com/949726/108068806-db1aba80-7062-11eb-9fea-515e882e8e4e.png)

-

**Comment by cannedit** [comment]
I am sorry, but I can't reproduce this issue (see the video attached), so would you please check again?

https://user-images.githubusercontent.com/22167327/108868707-c60bd180-75f6-11eb-95d2-a6639a22683b.mp4

**Comment by LarissaS** [comment]
It works fine. I've checked it in two browsers, don't know what it was, sorry!
