### ISSUE TITLE
mistakes in the email that new Ta request is created

### ISSUE THREAD

**Issue by LarissaS** [DiSSCo/ELViS#199]
#### Description
As a TA coordinator I've got a confirmation mail that new request is created. 
In the text "VA" should be changed to "TA";  link (url) is not working
Check also dots at the end of a sentences. 

Strange that for requests which I created under my institutional mail I did not get any notifications as a TA coordinator!

#### Steps to reproduce the issue

1.  
2. 
3. 

#### What's the actual result?

![image](https://user-images.githubusercontent.com/949726/108076188-744dcf00-706b-11eb-8b66-6550b6d9b89f.png)

**Comment by jgrieb** [comment]
I also experienced problems with the emails. I use two accounts, one with requester role & one with TA coordinator+requester role. When I submitted 2 TA requests via the requester account, I did not receive any Email at all as TA coordinator. When I submitted a TA request with the TA coordinator account itself, I received an Email. It had the same problem as above (text needs to be changed).

Also, the URL provided in the Email does not work, it would need to be changed to {frontendUrl/requests/ta/{id}

**Comment by mmarschler** [comment]
same here!

**Comment by cannedit** [comment]
This is solved now, please test.

**Comment by LarissaS** [comment]
Text ok, url prorvided does not work properly:
![image](https://user-images.githubusercontent.com/949726/111030244-65a3cf00-8401-11eb-83eb-87c86a6cc264.png)

**Comment by cannedit** [comment]
I noticed there is a subdirectory missing in the url in the email notification: "requests" should be: "requests/ta" (and the same for VA requests: "requests" should be: "requests/va"). We will fix this.
