### ISSUE TITLE
The confirmation email is not sent

### ISSUE THREAD

**Issue by jhusson** [DiSSCo/ELViS#2]
#### Description
On registration, the step 2, 

> You will receive a confirmation email 

is not working.

#### Steps to reproduce the issue

1.  Try to regisiter
2.  Wait the email confirmation
3.  Wait the email confirmation

**Comment by erwinmeesters** [comment]
Not a bug, just not build yet

**Comment by cannedit** [comment]
this ticket is added in Redmine as issue #46710
https://code.pictura-dp.nl/issues/46710
