### ISSUE TITLE
Password security

### ISSUE THREAD

**Issue by vixriihi** [DiSSCo/ELViS#20]
#### Description
Most likely due to this being an testing environment, but at the moment password is sent as plain text over insecure connection. Meaning that we're vulnerable to man-in-the-middle attacks.

#### Steps to reproduce the issue

1. Login or Register
2. Password is send as clear text over http to the server

#### What's the expected result?

- Testing could be done over https (maybe use a temporal cert from letsencrypt?)

#### What's the actual result?

- Password is sent over http an therefore any machine in the middle can sniff it.

**Comment by cannedit** [comment]
this ticket is added in Redmine as issue #46708
https://code.pictura-dp.nl/issues/46708

**Comment by wouteraddink** [comment]
We can only have a system in production with secure login, so I change the label to MVP ELViS
