### ISSUE TITLE
Radiobuttons selection problem in TA request form

### ISSUE THREAD

**Issue by jgrieb** [DiSSCo/ELViS#200]
#### Description
For any radiobutton in the TA request form, if the selected value is changed repeatedly (Yes->No->Yes), the 'No' option does not get unselected anymore and the radiobutton shows both values as selected (see screenshot below)

#### Steps to reproduce the issue

1. Create a new TA form
2. For any radiobutton, first select 'Yes', then select 'No', then 'Yes' again

#### What's the expected result?
A radiobutton should always only allow one option to be selected

#### What's the actual result?
The radiobutton shows that both 'Yes' and 'No' are selected, and I cannot change my answer to 'No' anymore. However, if I navigate to a different website and return to the TA requests it is displayed correctly again, so only the latest selected option was saved in the DB.

#### Additional details / screenshot
![ta_form_radiobutton_problem](https://user-images.githubusercontent.com/38728151/108345896-12ae7180-71df-11eb-9028-d9034a5e7373.png)
Tested with Firefox 85.0.1

**Comment by philippeloret** [comment]
I had the same problem.

![Capture d’écran de 2021-02-19 10-17-14](https://user-images.githubusercontent.com/75371870/108484547-37b4ea00-729c-11eb-8dfa-b1f4637fcd92.png)

**Comment by cannedit** [comment]
This has been taken care of, please test.

**Comment by jgrieb** [comment]
Tested: problem does not occur anymore
