### ISSUE TITLE
Comments for VA & TA requests not working anymore

### ISSUE THREAD

**Issue by jgrieb** [DiSSCo/ELViS#201]
#### Description
When I try to add a comment to a VA or a TA request it doesn't work anymore. After clicking 'Add comment' the wheel keeps spinning. Network analysis shows that an Http error 404 occurred upon posting the comment. This used to work before.

Could someone please confirm this issue or does it only happen to me?

**Comment by mmarschler** [comment]
Confirmed - I have the same problem!

**Comment by philippeloret** [comment]
Same problem when I tried to add comment.
![Capture d’écran de 2021-02-19 09-44-41](https://user-images.githubusercontent.com/75371870/108480584-7005f980-7297-11eb-8775-2aa23e69fe69.png)

**Comment by cannedit** [comment]
This has been taken care of, please test.

**Comment by jgrieb** [comment]
Tested it, comments work again in TA & VA request forms
