### ISSUE TITLE
Visibility/Filter all assigned TA requests for inst. moderator

### ISSUE THREAD

**Issue by mmarschler** [DiSSCo/ELViS#202]
#### Description
As an institutional moderater/TA/VA coordinator, I can see my assigned TA requests only when I filter the requests by clicking on "requests assigned to me". They are not shown in the list of all requests.
(Logged in as a requester, it works well: I can see my requests in the list of all requests as well as in the list of my own requests.)

List of all requests:
![2021-02-18_ELViS_instmod_allrequests](https://user-images.githubusercontent.com/75616869/108408335-3a282d00-7225-11eb-8389-7b34c1bea4c2.JPG)

Requests assigned to me:
![2021-02-18_ELViS_instmod_assignedrequests](https://user-images.githubusercontent.com/75616869/108408376-48764900-7225-11eb-943f-282730ef2657.JPG)

**Comment by LarissaS** [comment]
The same.
I also noticed that if I log in under inst. coordinator name (who is also VA coordinator) I only can see VA requests assigned to me, but not TA. Does it mean that inst. coordinator should also have a role of 'TA coordinator' to see all requests assigned to his institution?

**Comment by LarissaS** [comment]
I added a role of "TA coord." to institutional coordinator but request for TA are still not visible by filtering "assigned to me"

**Comment by cannedit** [comment]
@mmarschler so it works as expected for you?
@LarissaS actually I think it works as expected for you too: in case you are not a TA coordinator, then you should not be able to see any TA requests; in case you are a TA coordinator, then you should be able to see TA requests, but only the ones in which your institution is involved; it might be possible that after you added yourself as a TA coordinator to an institution no TA requests got connected to that institution anymore, so please check again by creating a TA request for the institution to which you assigned yourself as a TA coordinator.

**Comment by mmarschler** [comment]
@cannedit no, unfortunately not. I (as a TA/VA coordinator) expect to see all TA requests (that are assigned to me) in the "All requests"-list AND in the "Assigned to me"-list. This function works in VA, where I can find all VA requests that are assigned to me in the "All Requests"-list as well as in the "Assigned to me"-list. And it works too when I'm logged in as a requester, where I can find my TA & VA requests in both lists ("All requests" and "My own requests").
So in my opinion this should be fixed respectively harmonized. But it is not an urgent problem.

**Comment by LarissaS** [comment]
As a TA coordinator I see the requests for TA call (indeed only in "assigned to me"). But as an institution coordinator (also TA/VA coordinator) I don't see TA requests at all. It's important for institution coordinator to see ALL requests assigned to his institution, even if he is not TA/VA coordinator, no?
I also do not understand why I see (as TA coordinator) TA requests assigned to my institution which are NOT assigned to RMCA?

**Comment by cannedit** [comment]
We're working on this, but - to be clear - if you are not a TA or VA coordinator, it's normal that you don't see any TA or VA requests assigned to your institution, especially for TA requests, because it's important that only people directly involved in those are allowed to see those (see Github issue #170)

**Comment by mmarschler** [comment]
ok! thx, wim!

**Comment by cannedit** [comment]
This has been taken care of, please test.

**Comment by mmarschler** [comment]
it works perfectly well now! thx.
