### ISSUE TITLE
No i-icons in Resources needs > General

### ISSUE THREAD

**Issue by philippeloret** [DiSSCo/ELViS#205]
#### Description
There are no i-icons in Resources needs > General.
If "Access to collections" and "Access to libraries" fields are yes/no answer, may be radio buttons could be easier for requester. 

#### Additional details / screenshot

![Capture d’écran de 2021-02-19 10-51-02](https://user-images.githubusercontent.com/75371870/108488780-10145080-72a1-11eb-9208-4fbe9009dce8.png)

**Comment by cannedit** [comment]
We didn't receive any texts for this, in case this is needed or we have to change the texts themselves, please provide this info.
