### ISSUE TITLE
Error when requesting a visit to an institution 

### ISSUE THREAD

**Issue by B-San-Chi** [DiSSCo/ELViS#207]
#### Description
When making a visit request in the MNCN, an error appears:
"Something went wrong when selecting the National Museum of Natural Sciences. Is there a technical assistance coordinator assigned to this institution?" 

#### Steps to reproduce the issue

1.  Fill Type of request. Visit
2.  Fill Request title
3. Select the institution

#### What's the expected result? 
Open the rest of the fields of the request 

#### What's the actual result?
A phrase appears in red when selecting the Museo Nacional de Ciencias Naturales  and also the Real Jardín Botánico
"Something went wrong when selecting the National Museum of Natural Sciences. Is there a technical assistance coordinator assigned to this institution?" 
-

#### Additional details / screenshot

![imagen](https://user-images.githubusercontent.com/58851483/108685984-1d297d80-74f5-11eb-906b-ad9f7ddd4bba.png)

**Comment by cannedit** [comment]
That's actually a correct statement: you can't register a TA request in case there is no TA coordinator assigned to the institution you want to register a visit for (check the manual on this please). So in case you still need to register a TA request for that institution, you have to make sure it has a TA coordinator assigned.
