### ISSUE TITLE
confusing"submit" button in draft request

### ISSUE THREAD

**Issue by LarissaS** [DiSSCo/ELViS#211]
#### Description
I find that autosave function for a new request is quite confusing and draft requests will be submitted every time people want to press "save". I had to stop myself from pressing "submit" every time I made a new request. May be we could add (repeat) the text of the i-icon (at the top of request) just above "Submit" button, to warn people that it will be saved automatically and that they don't have to submit a request until it's done? 

#### Steps to reproduce the issue

1.  
2. 
3. 

#### What's the expected result?

-

#### What's the actual result?

-

**Comment by cannedit** [comment]
Hi @LarissaS, that info is already in the blue box info.

**Comment by LarissaS** [comment]
yes, I know. It is confusing to me, but we will see how it goes in the first call. It's not urgent enhancing in any case.
