### ISSUE TITLE
Broken link in email when users Register

### ISSUE THREAD

**Issue by scottwilson-nhm** [DiSSCo/ELViS#212]
The email people receive when they Register for ELViS includes a broken link

1.  Sign up for an account
2.  You receive an email
3.  Within which is a broken link (screenshot below)

Additional details / screenshot
![image](https://user-images.githubusercontent.com/58856468/109646279-e89a6f00-7b4f-11eb-9879-766edd8d6481.png)

**Comment by cannedit** [comment]
This is solved now, please test.
