### ISSUE TITLE
Not possible to choose amount of days in facilities in the first draft of request 

### ISSUE THREAD

**Issue by LarissaS** [DiSSCo/ELViS#213]
#### Description

While filling in the first draft I could not choose amount of days for facilities in host institution, it was everywhere "0"

Is this intentional?

#### Steps to reproduce the issue

1.  make draft request
2. choose dates, for example  for 5 working days
3. Go to resources needed, try to choose amount of days
4.  it is everywhere "0"
![image](https://user-images.githubusercontent.com/949726/110598050-9970c180-8181-11eb-9a73-c13a794674f6.png)
5. go out of request
6. go back
7. now you see "1,2,3,4,5" in amount of days
8. 
![image](https://user-images.githubusercontent.com/949726/110598745-65e26700-8182-11eb-9d11-481a0c106714.png)

Another question, if I choose two institutions to visit, why do I see in resources only facilities of one institute?

#### What's the expected result?

-

#### What's the actual result?

-

**Comment by cannedit** [comment]
@LarissaS I am sorry, but I can't reproduce this (see the video attached), so could you please check again?

https://user-images.githubusercontent.com/22167327/110614981-35ef8f80-8193-11eb-8d6e-df120ad257b2.mp4

**Comment by LarissaS** [comment]
Larissa Smirnova heeft een OneDrive voor Bedrijven-bestand met u gedeeld. Klik op de onderstaande koppeling om het bestand te bekijken.
<https://africamuseum-my.sharepoint.com/:v:/g/personal/larissa_smirnova_africamuseum_be/EWx1vpduYrpOvheVmINtKakB0skmfz1zvY9Tb0AZ9Y5vqA>
[https://r1.res.office365.com/owa/prem/images/dc-mpg_20.png]<https://africamuseum-my.sharepoint.com/:v:/g/personal/larissa_smirnova_africamuseum_be/EWx1vpduYrpOvheVmINtKakB0skmfz1zvY9Tb0AZ9Y5vqA>
ELViS - Google Chrome 2021-03-10 12-34-07.mp4<https://africamuseum-my.sharepoint.com/:v:/g/personal/larissa_smirnova_africamuseum_be/EWx1vpduYrpOvheVmINtKakB0skmfz1zvY9Tb0AZ9Y5vqA>

Sorry, Wim, I do not  know how to add video in Github, so I just send it to you.

Greetings,
Larissa

________________________________
Van: Wim van Dongen <notifications@github.com>
Verzonden: woensdag 10 maart 2021 11:25
Aan: DiSSCo/ELViS <ELViS@noreply.github.com>
CC: Larissa Smirnova <larissa.smirnova@africamuseum.be>; Mention <mention@noreply.github.com>
Onderwerp: Re: [DiSSCo/ELViS] Not possible to choose amount of days in facilities in the first draft of request (#213)


@LarissaS<https://github.com/LarissaS> I am sorry, but I can't reproduce this (see the video attached), so could you please check again?

https://user-images.githubusercontent.com/22167327/110614981-35ef8f80-8193-11eb-8d6e-df120ad257b2.mp4

**Comment by cannedit** [comment]
@LarissaS thanks, I was able to look at the video, but I see what went wrong: in the field "proposed length of visit" a dropdown appears with possible amounts of working days based on the start and end date you provided via the calendar options. But you then still have to select a value in that dropdown list, so either the full amount (in case of your video 5 days) or less, for example 3 or 4. So in case you don't make a selection in that dropdown list, then no amounts of days will be shown for the individual facilities. 

Please see the new video I attach here (this time in Chrome, the browser you also used, instead of Firefox in which my previous video was made).

Btw: you can attach a video here in Github, by clicking on the bar beneath this text field and then select your video.

https://user-images.githubusercontent.com/22167327/110626293-d6987c00-81a0-11eb-84bc-0169f04dadc2.mp4

**Comment by LarissaS** [comment]
Actually I did choose 5 days from the drop-down menu!

________________________________
Van: Wim van Dongen ***@***.***>
Verzonden: woensdag 10 maart 2021 13:02
Aan: DiSSCo/ELViS ***@***.***>
CC: Larissa Smirnova ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [DiSSCo/ELViS] Not possible to choose amount of days in facilities in the first draft of request (#213)


@LarissaS<https://github.com/LarissaS> thanks, I was able to look at the video, but I see what went wrong: in the field "proposed length of visit" a dropdown appears with possible amounts of working days based on the start and end date you provided via the calendar options. But you then still have to select a value in that dropdown list, so either the full amount (in case of your video 5 days) or less, for example 3 or 4. So in case you don't make a selection in that dropdown list, then no amounts of days will be shown for the individual facilities.

Please see the new video I attach here (this time in Chrome, the browser you also used, instead of Firefox in which my previous video was made).

Btw: you can attach a video here in Github, by clicking on the bar beneath this text field and then select your video.

https://user-images.githubusercontent.com/22167327/110626293-d6987c00-81a0-11eb-84bc-0169f04dadc2.mp4

**Comment by LarissaS** [comment]
I tried again today from the office and it works good, dropdown menus for facilities are not empty.
