### ISSUE TITLE
TA: "Download request" - resulting PDF is missing information

### ISSUE THREAD

**Issue by jgrieb** [DiSSCo/ELViS#214]
#### Description
When downloading the PDF of an approved TA request as a TA coordinator, the resulting PDF is not correct & misses information. It seems to be not updated yet to include the specific fields of TA requests

#### Steps to reproduce the issue

1.  Create a TA request
2.  As a TA coordinator, approve the TA request
3.  As a TA coordinator, in the request overview menu click the button to "download request"

#### What's the expected result?
A PDF report with all the fields that were filled out in the TA request

#### What's the actual result?
A PDF report with wrong title ("VA request") + most of the information that was entered in the form is missing (see screenshot below)

#### Additional details / screenshot
![grafik](https://user-images.githubusercontent.com/38728151/110616539-ef9b3000-8194-11eb-9f9b-5fd7a993fad7.png)

**Comment by cannedit** [comment]
@jgrieb yes, I noticed that too, we're working on solving this asap.

**Comment by cannedit** [comment]
See also Github issue #225.

**Comment by cannedit** [comment]
This is solved now, please test.
