### ISSUE TITLE
Production Server: Institutional information NHMW not visible

### ISSUE THREAD

**Issue by mmarschler** [DiSSCo/ELViS#215]
On the production server, institutional information for NHMW (adress, affiliated location etc.) is not visible. 
In other institutions the information is shown, and for NHMW it is also shown at the acceptance server (see screenshots below).

Browser: Firefox 85.0.1 (64-Bit)

**production server:** 
![2021-03-10_production_server_institutionalinformation](https://user-images.githubusercontent.com/75616869/110682525-4e839800-81db-11eb-8f13-77e500814fb9.JPG)

**acceptance server:**
![2021-03-10_acceptance_server_institutionalinformation](https://user-images.githubusercontent.com/75616869/110682552-59d6c380-81db-11eb-9b34-5e8803519cde.JPG)

**Comment by cannedit** [comment]
We will take care of this.

**Comment by cannedit** [comment]
This is solved now, but will not be visible until we deploy the latest version of ELViS to the Production server on Monday morning, the 15th of March.

**Comment by cannedit** [comment]
This will be taken care of once we deploy on the ELViS production server
