### ISSUE TITLE
Selected institution not visible in profile page

### ISSUE THREAD

**Issue by vixriihi** [DiSSCo/ELViS#216]
#### Description
When I registered a new person to FMNH on that persons profile page it shows
"Institution: Naturalis Biodiversity Center"

#### Steps to reproduce the issue

1.  Register a new account
2.  Select institution
3.  Go to profile

#### What's the expected result?

- Selected institution to be visible

#### What's the actual result?

- Institution: Naturalis Biodiversity Center is selected

#### Additional details / screenshot
Profile page:
![image](https://user-images.githubusercontent.com/5203261/110749048-3fd3ca00-8249-11eb-965c-426105c8dd24.png)

Institute people page:
![image](https://user-images.githubusercontent.com/5203261/110749177-6abe1e00-8249-11eb-889e-da9520e58373.png)

**Comment by cannedit** [comment]
We will take care of this.

**Comment by wouteraddink** [comment]
A similar thing is happening when you try to edit your profile later, if you select an institution, it is not immediately displayed in the saved result, and if you navigate away and come back to your profile, Naturalis is selected (independent of which institution you selected).

**Comment by cannedit** [comment]
We're working on this. This is probably related to adding Naturalis last minute as an extra institution. We don't have functionality to add institutions in the front-end yet, so this had to be taken care of 'under the hood'. So this is something to scope for the 2nd development phase.

**Comment by cannedit** [comment]
This is solved now, please test.

**Comment by wouteraddink** [comment]
confirmed
