### ISSUE TITLE
Some characters in comments break the pdf download

### ISSUE THREAD

**Issue by vixriihi** [DiSSCo/ELViS#217]
#### Description
For example here https://elvis-accept.pictura-hosting.nl/calls/7d4cc4af-ac72-406e-b128-0edb23e48659/edit-va-request/570b786b-88be-4752-80e7-c3e8462106f9 the angle bracket break pdf generation

#### Steps to reproduce the issue

1.  add angle bracket in the comment
2.  download comments as pdf

#### What's the expected result?

- pdf with all the comments

#### What's the actual result?

- pdf fails to load

**Comment by cannedit** [comment]
Sorry, but I can't see what goes wrong, can you be a bit more specific, like mentioning what characters cause this problem and maybe send a screenshot of the comments discussion?

**Comment by cannedit** [comment]
Ok, so < > can be used in a comment, but this breaks a proper PDF generation, so I would say: workaround for now is to avoid these characters in comments. Unless you can point me to other characters which will cause problems and which might be necessary to use in comments, I would say, this is something we can take care of at a late stage of the project.

**Comment by vixriihi** [comment]
Error seems to be caused by < character (> can be there and there is no issues with only that). If I add `&lt;` then the < character prints correctly to pdf but in the comments not. Example in here: https://elvis-accept.pictura-hosting.nl/requests/va/fc6267a2-f572-4731-a2ca-a0ea93f5bfec?orderBy=requestDate&direction=asc&perPage=10&q=

**Comment by cannedit** [comment]
Ok, thanks, we will try to solve this.

**Comment by cannedit** [comment]
This is solved now, please test.

**Comment by vixriihi** [comment]
works
