### ISSUE TITLE
sending email fails on production

### ISSUE THREAD

**Issue by wouteraddink** [DiSSCo/ELViS#218]
#### Description
If I go to login on production (elvis.dissco.eu, v0.6.8) and click Forgot Password? then I get the message:

 Failed to send email, please try again later.

**Comment by wouteraddink** [comment]
if I send a support request on production, then I get the message that the request has been sent though, but it also says that an email has been sent to me, which did not arrive. I guess it is the same issue with sending email not working, but different behavior.

**Comment by cannedit** [comment]
This has already been identified as a problem and we're working on it.

**Comment by cannedit** [comment]
The issue with the password recovery functionality has been dealt with, please test.

**Comment by wouteraddink** [comment]
password recovery function is working now, email notification on support question is not working.

**Comment by cannedit** [comment]
The email notification is out of scope for ELViS v1 (it will be dealt with once we connect ELViS to the new DiSCCo helpdesk system), and the message after sending the helpdesk request is now adapted accordingly. Please test.

**Comment by wouteraddink** [comment]
Notification is ok on acceptance, not yet on production but I assume it will work there as well with new deployment so I mark as resolved.

**Comment by wouteraddink** [comment]
Actually I do receive an email notification now! so the notification was ok..
