### ISSUE TITLE
it seems to be possible to submit draft requests after the call closed

### ISSUE THREAD

**Issue by FB-MfN** [DiSSCo/ELViS#222]
Description
As a requester I was able to submit a draft request after closing of the call. By coincidence I left a request in draft mode on March 10th, which I submitted now during the temporary closure of the TA call.
Is that an expected behviour because we are dealing with "soft" deadlines?

**Comment by cannedit** [comment]
No, that is not expected behaviour, so please try to organise such a test scenario again in cooperation with an admin (@scottwilson-nhm or @wouteraddink)
