### ISSUE TITLE
problems when deleting selected institution in TA request

### ISSUE THREAD

**Issue by wouteraddink** [DiSSCo/ELViS#223]
#### Description
when selecting an institution for a new TA request, the rest of the forms appears and a select list is also displayed for other institutions in the TAF, which is as expected.
But if you selected the wrong institution and deselect it, when selecting another one the rest of the form does not appear anymore and all institutions of all TAFs can be added.

![ta request screenshot](https://user-images.githubusercontent.com/395870/110776184-0d819700-8260-11eb-810d-e8ac164373e1.png)

**Comment by wouteraddink** [comment]
NB if you navigate away and try again by selecting the draft TA request it works ok again

**Comment by cannedit** [comment]
We will try to take care of this in time.

**Comment by cannedit** [comment]
This is solved, so please test.

**Comment by wouteraddink** [comment]
confirmed.
