### ISSUE TITLE
Hide Main Menu item "Requesters" for anyone except Admins and TAF Admins

### ISSUE THREAD

**Issue by cannedit** [DiSSCo/ELViS#231]
#### Description
NHM Evaluation Excel sheet no. 1:
All requesters can see name, e-mail, gender & ORCID ID of all ELViS-registered users. Requesters' personal information should be visible only to the requester themselves and to TAF administrators / Risk of information mis-use.

#### Agreement
We will solve this 'Quick and Dirty': make the Main Menu item "Requesters" only visible for Admins & TAF Admins

**Comment by LarissaS** [comment]
as a regular user I do not see Requesters, only Requests. But in Request I can see a name, email and orcid id of a requester.

**Comment by cannedit** [comment]
That's correct, but this is a Quick and Dirty method to solve the main problem: anyone having access to all profile info of al requesters. In case you can see a request, you are probably involved in that request one way or another (at least for TA Call requests), so then it's hard to hide names/email addresses/orcid id's of other requesters involved.

**Comment by emhaston** [comment]
I have two accounts. One is my VA-coordinator account (e.haston@rbge.ac.uk) and one is my requester, non-admin account (e.haston@rbge.org.uk). I can see all the requesters from both accounts, including e-mail and gender information.

**Comment by emhaston** [comment]
First, I need to check I'm testing the correct test version! :). I can't see Requesters tab in either my admin or my regular account. I can see 72 requests in both my regular and my admin accounts.

**Comment by philippeloret** [comment]
It's ok, I cannot see the main menu item "Requesters" (only Requests).

**Comment by B-San-Chi** [comment]
Ok also for me,  I only see Requests in both cases

**Comment by cannedit** [comment]
@emhaston: you should be able to see the main menu item "Requesters" when logged in with an admin account, but not with your regular (requester role only?) account; can you please verify this?

**Comment by wouteraddink** [comment]
for user without extra roles (requester), the roles overview in the profile looks a bit weird:
Institution based -
Roles -
Country based -
Roles -

Is this what I am supposed to see? I find this overview confusing for the requester.

**Comment by wouteraddink** [comment]
Under the institutions/people tab, you can as requester still see the email addresses from all people.

**Comment by cannedit** [comment]
@wouteraddink: 
I think the info about employees of institutions can be useful in case someone wants to contact somebody from an institution. As for the (empty) summing up of roles for common users (without extra roles) looking weird: this is an indication that it is possible to have roles, so I think we should change this functionality, but rather explain it in the user manual.

**Comment by cannedit** [comment]
See Github issue #240 and in addition: the labels "Institution based" and "Country based" are now changed.

**Comment by mmarschler** [comment]
For me the wording is ok.

**Comment by LarissaS** [comment]
The wording is ok now. But I agree with Wouter that every requester can see now email addresses of people affiliated  to the institution. If people have a role like TA, VA coordinators, then it's ok, But for other people affiliated to the institution but without possibility to specify their position at the institution, like curator of certain collection of head of a department, for example, then it has no sense that requestors see these email addresses. And if people use private email address it will be visible too.

**Comment by wolodkin** [comment]
As a new user I wasn't sure what's meant at first : 

Roles for Institution -
Roles - 
Roles for Country -
Roles -

I would prefer to use a phrase like "You are a ROLE at..." if there ist a role.

**Comment by cannedit** [comment]
@LarissaS @wolodkin: I understand your comments, but we decided in the WP6 meeting upon the wording as well as only hide the role of TA Scorer in the tab "People" per Institution.
