### ISSUE TITLE
Add two extra fields for user registration and profile

### ISSUE THREAD

**Issue by cannedit** [DiSSCo/ELViS#232]
#### Description
NHM Evaluation Excel sheet no. 3:
Enhancement of User Profiles: capturing Home Institution, Nationality, & other details / Most of the workload for TA Coordinators was establishing fields like Home Institution, etc. User profiles should capture the profile outline that was available on the old portal - only visible to TAF Admins, TA Coordinators, VA Coordinators, and superadmin.

#### Agreement
We're going to expand the user profiles with two extra fields: Home Institution and Nationality.

**Comment by emhaston** [comment]
I can see Employed by participating institution, Employed by other institution and Nationality. The Employed by fields are not very intuitive.

**Comment by philippeloret** [comment]
This is good for me. I see "Nationality", "Employed by participating institution" and "Employed by other institution".

**Comment by cannedit** [comment]
@emhaston what do you mean with: "The Employed by fields are not very intuitive"?
