### ISSUE TITLE
Connect the ELViS Helpdesk page form to the DiSCCo Helpdesk tool

### ISSUE THREAD

**Issue by cannedit** [DiSSCo/ELViS#237]
Description

At the moment the ELViS Helpdesk page offers a form to ask questions about ELViS or to report problems while using ELViS which sents an email to this email address: synthesys@nhm.ac.uk.

Since there is now a DiSCCo Helpdesk tool available (https://dissco.jitbit.com/), which is able to turn emails into helpdesk tickets, the current email address to which the ELViS Helpdesk page sends info to will be changed into this DiSCCo Helpdesk tool's email address: support@dissco.jitbit.com (and of course the text on the ELViS Helpdesk page will be adapted accordingly).

**Comment by wolodkin** [comment]
I have tried to upload a file with 25,0 MB (maximal size) from https://www.dasinternet.net/file.php?file=leil.de/di/files/more/testdaten/25mb.test but it wasn't possible: "The filesize exceeds 25 Mb, please upload a smaller file".

**Comment by philippeloret** [comment]
I tried to send "Questions and Feedback" and it's ok. But the mail I received is malformed : The beginning of my first name was replaced by an emoticon because there is a : just before my first name (Message from :Philippe L...). I think a space between the : character and the first name could avoid this situation
![elvis_questions_feedback_email](https://user-images.githubusercontent.com/75371870/156176681-90bef6f0-59a7-4765-99aa-3645c245274c.png)
.

**Comment by B-San-Chi** [comment]
I have tried to send a file in "questions and feedback" and the answer was
"Something went wrong uploading the form, please try again"

**Comment by B-San-Chi** [comment]
I can not connect to DiSCCo Helpdesk tool

**Comment by philippeloret** [comment]
Me too, I cannot log in to DiSSCo Helpdesk tool.

**Comment by B-San-Chi** [comment]
For me the e mail received is ok
![ELViS_answer pdf](https://user-images.githubusercontent.com/58851483/156177996-adfa3e59-b2fd-4b43-ad55-3aba14d884e8.png)

**Comment by cannedit** [comment]
@wolodkin: yes there seems to be something wrong with the limit for uploading a file, just a small one will do, but larger ones (like beyond 10 Mb) not, we will fix this.
@philippeloret and @B-San-Chi: thank you for spotting the issue with the colon, we will correct that; but getting access to the DiSCC0 helpdesk tool is not part of this functionality, so I will discard these remarks.

**Comment by wouteraddink** [comment]
I could send a help message and received the confirmation email. Attachment also included. However mails do not seem to arrive in the jitbit helpdesk, there are no new emails in jitbit from the test period.

**Comment by cannedit** [comment]
@wouteraddink:
Regarding no emails from ELViS ending up in the DiSCCo helpdesk system: I will let the team check whether we use the correct email address ofc, but I think we need to check things with the persons responsible for the DiSCC helpdesk system too: for example whether the url of the ELViS Acceptance server is not being blacklisted somehow.

**Comment by cannedit** [comment]
The lay-out of the email messages has been adapted, so @philippeloret the issue you encountered before will not occur anymore, however: we're still working on the problem that emails don't arrive in the DiSCCo JitBit system is still under investigation.

**Comment by mmarschler** [comment]
I tested this once more, and there is another layout problem in the email message: There are some \n in the text (see screenshot).
![2022-03-17_email_from_helpdesk](https://user-images.githubusercontent.com/75616869/158789072-2d4e451b-cb8d-4bac-a21f-11d613f4ce03.PNG)

**Comment by mmarschler** [comment]
I just tested the maximum size of attachments - everything is ok! As requested, it is limited to 4 mb, and this limit is shown also in the i-icon next to the upload button. If it's more than 4 mb, the proper error message is shown:

![2022-03-17_helpdesk_4mb_error](https://user-images.githubusercontent.com/75616869/158802587-9923e33e-ed24-4211-ab81-498a2d83a205.PNG)

**Comment by B-San-Chi** [comment]
I just tested the form again. I have the same problems as mmarschler

![imagen](https://user-images.githubusercontent.com/58851483/158807506-ca4baf3d-11ca-435e-ad3c-cc741dfe319a.png)

**Comment by LarissaS** [comment]
I sent a test question (with attachment) and got the confirmation email. So it works fine. 
![image](https://user-images.githubusercontent.com/949726/159010698-5d995152-fd4e-4707-a97e-2bf55f2708c0.png)

**Comment by B-San-Chi** [comment]
Yes but continue writing \n  in the first two lines 
It is right?

**Comment by LarissaS** [comment]
> Yes but continue writing \n in the first two lines It is right?

yes, it looks a bit strange, indeed!

**Comment by cannedit** [comment]
@mmarschler @LarissaS @B-San-Chi: we will fix the "\n"-issue (it was an attempt to spread the message over more than one line, but apparently that only works in a few email systems) and we will also adapt the error message accordingly in case a too large attachment is sent along with a helpdesk message.

**Comment by cannedit** [comment]
@mmarschler @LarissaS @B-San-Chi @wouteraddink in addition: we will check again why the emails from the ELViS Helpdesk form don't arrive in the DiSCCo helpdesk system.

**Comment by cannedit** [comment]
Due to the fact that helpdesk requests sent via the webform on the ELViS helpdesk page don't arrive in the DiSCCo helpdesk system JitBit, whereas requests for help sent directly via user's standard computer mail functionality do arrive in the DiSCCo helpdesk system, we decided to suppress the webform in the ELViS helpdesk page and to make the email address of the DiSCCo helpdesk system to which requests for help should be addressed clickable to connect it to the user's standard computer mail functionality. In addition we elaborated a bit more on the helpdesk functionality on the ELViS helpdesk page, by extending the text over there. This workaround can now be tested on the ELViS Acceptance server.

**Comment by mmarschler** [comment]
The new workaround works well: Email was clickable and computer mail programme opened a new mail. I sent two testmails with different attachments. Larissa and Pat confirmed the receipt.

I can also see my tickets when I click on the dissco-jitbit-link that is sent with the confirmation email.

But I was not able to log in at jitbit (https://dissco.jitbit.com/helpdesk/, as suggested in the Q&A-text) with my usual ELViS password. So I had to use the HelpDesk password recovery (which worked fine), and now everything is ok.

**Comment by cannedit** [comment]
@mmarschler I may have overlooked something, but I don't think the helpdesk page text in ELViS suggests that it is possible to use your ELViS credentials to log into the JitBit system.
