### ISSUE TITLE
TA Call Request Scoring functionality

### ISSUE THREAD

**Issue by cannedit** [DiSSCo/ELViS#238]
The Scoring functionality for approved TA Call Requests has been implemented (see the manual page 51-54).

This can be handled by a person holding the TA Scorer role (per country) and the general admin

**Comment by LarissaS** [comment]
as a regular user I created a request for RMCA (title "My 2nd request") and submitted it. Logged in as TA coordinator Arnaud Henrard I do not see it in requests assigned to me. I have the impression that I don't see any requests from a new 2022 call.

**Comment by cannedit** [comment]
I guess this comment is actually referring to Github issue #236, but I can react on it over here anyway: it's still the idea that there can only be one TA Coordinator per institution and at the moment both Arnaud Henrard and you hold that role, so please correct this and check again?
![ELViS_TA_Coordinator_RMC](https://user-images.githubusercontent.com/22167327/155747155-df766197-b822-440e-a326-005f6c00c0a0.png)

**Comment by wolodkin** [comment]
- As a requester I created a request "Alex' test request". 
- After I renamed the title to "Alex' test request (renamed)". 
- After an update of some texfields a don's see any errors. 
- Finally I renamed my request to "Alex' test request (updated, renamed)".

_In contrast, the testers *without* Admin or TAF Admin rights are asked 
to test whether they, as requesters, can see the name, e-mail, **gender** & 
ORCID ID of all ELViS-registered users._ 

There is no information about the gender.

**Comment by cannedit** [comment]
@wolodkin: I guess your comment is a result of testing Github issue #231 ?

**Comment by mmarschler** [comment]
The scoring functionality seems to work properly. I tested it with several different accounts, and I can see and score only requests for which I have the role TA scorer.

Concerning the status "scored": In TA calls, we have 4 scorers for each institution/request. To my understanding, now the status of the request is "scored" if only one scorer has finished scoring and therefore indicates that this request is "complete", although not all 4 scorers have finished scoring. So this could be a major issue for TAF admins to check if all requests have really been completely scored. Maybe we can add an additional status "under scoring" as soon as one scorer has scored, and "scored" only if all 4 scorers have scored? 

Furthermore, the manual says that admins can check scoring. Do you really mean admins or TAF admins? As so far, this work was done by the TAF amins in the course of preparations for the User Selection Panel.

**Comment by mmarschler** [comment]
Concerning the visibility of requests in "Requests assigned to me":

Logged in with our Synthesys-Team account, which has among others the roles TA coordinator and TA scorer (see screenshot), I can see under "all requests" all requests for our institution as well as the requests for which I have the scorer role - so this works perfectly fine.
![2022-03-02_TA_coordinator_Vienna](https://user-images.githubusercontent.com/75616869/156370345-15c73d33-016f-49b1-976c-489265b3713d.PNG)

![2022-03-02_all_requests_Vienna](https://user-images.githubusercontent.com/75616869/156370361-fc36c583-d4c5-47b4-a77e-50f3367f000d.PNG)



But when I filter the "Requests assigned to me", I can only see the requests for which I have the scorer role. Here I don't see the requests for our institution anymore:
![2022-03-02_requests_assigned_to_me_Vienna](https://user-images.githubusercontent.com/75616869/156370370-73305b6d-1949-4e4d-8cdd-d2a9138f9bf0.PNG)

**Comment by mmarschler** [comment]
One more issue: The manual says that a TA scorer will see TA call requests once the TA call's deadline has passed (see Manual page 51). I was able to score the requests although the call has not ended yet.

**Comment by mmarschler** [comment]
And could you please give the TAF admin role to our Synthesys-team account synthesys@nhm-wien.ac.at ? Then I will check the soring functionality also from this point of view. Thank you!

**Comment by cannedit** [comment]
@mmarschler:
We never received the ‘requirement’ that TA Call Requests had a fixed amount of TA Scorings as you suggested (4), so the functionality is implemented in such a way that a TA Scoring can happen multiple times (up to the Admins to decide, via assigning TA Scorers). So in case we have to change this set up, then it will mean much more than just adding an extra scoring status. 
Regarding the statements about TA Scoring in the manual: we will correct them ofc, but there is only a deadline for scoring and the starting date is actually termined by two things: 1. an Admin assigning the TA Scorer role, and 2. the approval of TA Call Requests, so in this sense the Admin actually decides the start of the TA Scoring period. 
As for you not being able to see anymore requests than the one you are supposed to score, despite the fact that you are also a TA Coordinator: this is the result of mixing these two roles. The original idea was that a TA Scorer should be independent, so not being a TA Coordinator involved in TA Call Requests and thus this is correct.
Finally: I have just changed the role of the synthesys@nhm-wien.ac.at account from TA Scorer for Belgium into TAF Admin for Belgium.

**Comment by LarissaS** [comment]
Hi,
I updates the roles and now if I am logged in as TA coordinator I can see requests assigned to me.

Best,
Larissa

**Comment by mmarschler** [comment]
@cannedit: 
It really seems to be an issue of mixed roles. Once I've gave the ta coordinator role away from synthesys@nhm-wien.ac.at to maria.marschler@nhm-wien.ac.at, it worked perfectly fine: 
Logged in as maria.marschler (ta coordinator), I can see all requests for NHMW (in "All requests" as well as in "Requests assigned to me"). 
Logged in as synthesys (taf admin for Belgium), I can only see all Belgium requests (in "All requests" as well as in "Requests assigned to me"), but no NHMW requests anymore.

So I think everything is fine now!

**Comment by LarissaS** [comment]
I have now three roles, ***@***.******@***.***> as TA coordinator, ***@***.******@***.***> as requester and ***@***.******@***.***> as institutional moderator and VA coordinator.
As TA coordinator I see all requests assigned to me, as  institutional moderator I do not see any TA requests, is it normal? Now Arnaud ***@***.******@***.***>) is assigned a role of moderator and VA coordinator. Shell we separate these two roles too?
Wim, can you give Arnaud a role of TAF administrator, then I can test the scoring functionalities too, if it is still needed of course.

Best,
Larissa

**Comment by B-San-Chi** [comment]
"As it is the same case that happens to Larissa S, in the MNCN there is not a correct assignment of roles and it has caused that in previous TA calls we have had problems. With the idea that there should be only one TA coordinator per institution, this role should only be held by Josefina Cabarga and not by Marian Ramos, since in this way the TA requests reach the wrong person.
Wim, could you correctly assign this role only to Josefina and remove it from Marian, as I indicate below?"
[TA1.pdf](https://github.com/DiSSCo/ELViS/files/8304835/TA1.pdf)
[TA2.pdf](https://github.com/DiSSCo/ELViS/files/8304836/TA2.pdf)

**Comment by LarissaS** [comment]
Who assigns the role of score? The manual says admin, but what admin, not TAF admin? Is there already a scorer for Belgium? I can't test the scoring functionality, because I don't even see how can I assign request for scoring!
