### ISSUE TITLE
CETAF links broken  in institutional pages

### ISSUE THREAD

**Issue by wouteraddink** [DiSSCo/ELViS#239]
#### Description
The CETAF links in the institutional pages are currently broken, as CETAF changed their urls. The Institutions cannot change these themselves in ELViS. What would be needed is to use an url with the known GRID ID in the format: https://darwin.naturalsciences.be/cetaf_institutions_resolver/resolver.php?grid_id=grid.425433.7 

instead of:
https://cetaf.org/botanic-garden-meise-0

**Comment by cannedit** [comment]
It's now possible for Institution Moderators to change that weblink in the Acceptance server, so please test this and then we can ask Institution Moderators to change this in the Production server, the minute the new functionality is available over there, envisaged for just before the start of the new TA Call in April.

**Comment by mmarschler** [comment]
Ok! Changing the CETAF identifier-link worked fine.

**Comment by LarissaS** [comment]
I can change the link, it works fine.
