### ISSUE TITLE
minimum viable product institution specification 

### ISSUE THREAD

**Issue by wouteraddink** [DiSSCo/ELViS#24]
#### Description

[MVP_ELViS_Workflow_institution specification.pdf](https://github.com/DiSSCo/ELViS/files/4036292/MVP_ELViS_Workflow_institution.specification.pdf)

**Comment by wouteraddink** [comment]
I would suggest to import already available data.

- identifier: use GRID.AC identifier. For institutions that don't have one yet, use temporarily a custom one
- acronym: not really needed for VA call, can be taken from CETAF passport
- name of institution: use from GRID metadata
- address of institution: not really needed for VA call, can be taken from CETAF passport
- country: use GRID metadata (can also point on a map with this data but not really needed), or from CETAF if GRID metadata not available
- general email address of institution: not really needed for VA call
- website of institution: get from GRID, or from CETAF if GRID not available

I would also add:
- wikidata url (from GRID)
- cetaf passport url
- gbif dataprovider url

I would also store and display the source from which the data was derived.

Facilities, CMS, list of collections may import from already available data

Note that in the future institutional data should be a separate service and may contain quite a lot of data. Part of this can be displayed in ELViS, like address for visit request, postal addres for loans, acronym for dashboards etc.

Note also that later if we want to link people to institutes through their ORCID and GRID, we may encounter that some ORCIDs are linked not directly to a GRID of a museum but to the GRID identifier of the parent University.

**Comment by Karin-Wiltschke** [comment]
Naturhistorisches Museum Wien is twice in institutions

please delete
grid.507655.4 | Naturhistorisches Museum WienGermany Berlin
-- | --

**Comment by Karin-Wiltschke** [comment]
please correct
http://elvis-accept.pictura-hosting.nl/calls/7d4cc4af-ac72-406e-b128-0edb23e48659
9 Partners to 19 Partners (entrance sentence)
