### ISSUE TITLE
Hide the mentioning of the TA Scorer role in the tab "People" of an Institution

### ISSUE THREAD

**Issue by cannedit** [DiSSCo/ELViS#240]
During the WP6 meeting on March 8 2022 we decided that it's Ok that the email addresses and roles of users linked to an Institution are still shown in the tab "People" of the Institution, but that an exception should be made for the role of TA Scorer because he/she has to do the scoring anonymously.

This is now solved, so once an ELViS user gets the role of TA Scorer, this will not be mentioned in the tab "People" of the Institution he/she is working for.

**Comment by B-San-Chi** [comment]
Ok, I am only seeing the item "Requesters" from the main menu as a VA coord, not as an applicant

**Comment by mmarschler** [comment]
Works fine, TA scorer isn't mentioned anymore in the "People"-tab of the institution.

**Comment by LarissaS** [comment]
I do not see the role " scorer" anymore. Who can assign the role "scorer"? TAF admin? I tried to find our, but could not.

**Comment by cannedit** [comment]
@LarissaS at the moment only a general Admin can assign the TA Scorer role, but we're working on allowing a TAF Admin to do that too, however, that's not in the current Acceptance server deployment yet, so hopefully in the next one.

**Comment by megumi-nhmw** [comment]
I don’t see the “scorer” neither. However, in testing this topic, I found that the role “institution moderator” is mentioned multiple times at some institutions. It probably has nothing to do with the issue #240, but I just want to let you know.
![Screenshot (15)](https://user-images.githubusercontent.com/100203553/159303075-396011f2-aee5-4e16-a200-bf0f0a264daa.png)
![Screenshot (17)](https://user-images.githubusercontent.com/100203553/159303501-228f339a-0267-4603-a688-543f66b954dc.png)

**Comment by cannedit** [comment]
@megumi-nhmw thank you, I was able to solve (as an Admin) in the interface the fact that some users had multiple mentioning of their Institution Moderator role in the tab "People" of their Institution, so that's not happening at the moment anymore, but I will nevertheless ask the team to look into this.
