### ISSUE TITLE
A TAF Admin should also be able to assing the role of TA Scorer

### ISSUE THREAD

**Issue by cannedit** [DiSSCo/ELViS#242]
At the moment only a general Admin can assign the role of TA Scorer to an ELViS user and in this way he/she can kick-off the start of the scoring period for a TA Call. However, it would be nice if a TAF Admin will also have the possibility to assign that role, thus being able to kick-off the start of the scoring period for a TA Call for his/her country.

**Comment by mmarschler** [comment]
I tested as TAF Admin assigning the scorer role, but it didn't work properly. I was able to assign it, but the role is not saved.

**My TAF Admin profile (TAF Admin of Belgium):**
![2022-04-12_profile_TAF_admin](https://user-images.githubusercontent.com/75616869/162928652-5d4b11da-d1db-480c-8c0a-29b936039fce.PNG)

**Assigned role for a requester:**
![2022-04-12_assigning_ta_scorer_Belgium](https://user-images.githubusercontent.com/75616869/162928951-13e101c2-cbe3-47f3-b11e-0706d653ad32.PNG)

**Logged in with requester/TA scorer-account, no role visible in profile:**
![2022-04-12_profile_ta_scorer_Belgium](https://user-images.githubusercontent.com/75616869/162929044-6ba888b1-ac27-4a2d-95ad-f20052dbf31f.PNG)


I tested the same with Austria. Again, I was able to assign it, but it is not saved.

**Comment by cannedit** [comment]
@mmarschler I see, we will correct this.

**Comment by cannedit** [comment]
@mmarschler we have solved the issue now, so would you please try again?
