### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by timrobertson100** [DiSSCo/ELViS#26]
Is ELViS content exposed through an API, and if so, is there any documentation?

**Comment by sharifX** [comment]
Hi @timrobertson100 

In the ELViS design document, we talked about exposing content through an API. For example, loan status data for a specimen can be retrieved with an API call and as a JSON object. However, at this point, we do not have any detailed documentation. We will try to do so in the next few months (discuss API design, requirements, create API design diagrams etc.). 

We do have several [user stories](https://github.com/DiSSCo/user-stories/issues?q=is%3Aissue+is%3Aopen+label%3AIntegration)  that indicated the need for API and other integrations. We are also working/testing with [Cordra ](https://www.cordra.org/) -- a Digital Object repository -- to see how the ELViS front end and federated AAI can work with Cordra.  Cordra provides both REST and DOIP (Digital Object Internface Protocol) [interface](https://www.cordra.org/documentation/api/introduction.html).

**Comment by timrobertson100** [comment]
Thanks @sharifX 
(I'm familiar with Cordra and it's internals)
