### ISSUE TITLE
replace elvis logo with Synth logo

### ISSUE THREAD

**Issue by wouteraddink** [DiSSCo/ELViS#29]
#### Description
Replace ELViS logo with Synthesys+ logo for the system to take into production Feb 20, to avoid confusion with full ELViS development.
![image](https://user-images.githubusercontent.com/395870/73249035-5ee1da80-41b4-11ea-84ba-b0a03658d409.png)

**Comment by cannedit** [comment]
this ticket is added in Redmine as issue #47172
https://code.pictura-dp.nl/issues/47172

**Comment by wouteraddink** [comment]
Hi Wouter,
Looks great. Note that you might want to use the attached reversed PNG as the logo. This will look a little more professional against the header. There is a minor clash with the header colour on the "A DiSSCo Project" text and one of the bands of the SYNTH logo but it looks better than the non-reversed option you are currently using. If you want to, feel freed to do a minor tweak on the text and band to make these stand out more against the header.

Best regards,

Vince

![SYNTHESIS+_logo_rev](https://user-images.githubusercontent.com/395870/74935187-223a8500-53e8-11ea-9363-b1ad01050cea.png)

**Comment by wouteraddink** [comment]
The Picturae team would all like to see bringing back the original ELViS logo on the homepage again as such. Of course this needs to reflect that the system which we will launch later today is only a first step of this system, aimed at facilitating the first VA Call, so I took the liberty to amend the old original homepage a bit, mixing it with the text from the current homepage. Please find this mockup attached.

Wim

[NewLayoutHomepageProposal.docx](https://github.com/DiSSCo/ELViS/files/4230762/NewLayoutHomepageProposal.docx)

**Comment by wouteraddink** [comment]
The request to not yet use the logo was to match expectations and to match the project description that says this is a temporary system and not yet ELViS. 

I am not against using the ELViS logo as long as we find a solution that deals with this concern. Sharif and I looked at your proposal and we think it does not deal sufficiently with these concerns yet, so I propose to do this (if there is time) but with a few changes:

- create a slightly modified logo that says: ELViS VA
- keep Virtual Access applications portal as the subtitle or remove "portal"
- use as text:
Towards a European Loans and Visits System + your text.
- In your text replace "This first version" with "This earlier version" to avoid confusion with ELViS version 1 as described in the project to deliver at the end of the year.
- move the Synth+ logo to the bottom next to the DiSSCo logo as this is a Synth+ project result.

**Comment by wouteraddink** [comment]
Just a note that we will also need to display the European emblem (flag) to acknowledge the support received under EU programme. IT can be downloaded from: https://europa.eu/european-union/about-eu/symbols/flag_en
See also: https://ec.europa.eu/easme/en/section/communication-toolkit

so we need, besides the ELViS logo, three other logos: [link:synthesys.info]Synth+, [link:dissco.eu]DiSSCo and [link:ec.europa.eu]EU. With a statement saying:
developed in the SYNTHESYS+ project with funding from the European Union’s Horizon 2020 research and innovation programme under grant agreement [link:https://cordis.europa.eu/project/id/823827]ID: 823827.

**Comment by mnwdeboer** [comment]
redmine issue #47796
