### ISSUE TITLE
Wrong error color on e-mail form

### ISSUE THREAD

**Issue by jhusson** [DiSSCo/ELViS#3]
#### Description
When you type a bad format e-mail on registration form, the cell is checked as OK and surrounded in green as well as the return error message.

#### Steps to reproduce the issue

1.  Type an email with bad format, i.e myname@myserveur
2. Click outside

#### What's the expected result?

- The cell should be red or orange with the same color for the return error msg

#### What's the actual result?

- The cell is checked as OK
- The cell is surrounded by green
- The return error message is green

#### Additional details / screenshot

![elvistest1](https://user-images.githubusercontent.com/6170651/71357114-ca68d480-2584-11ea-8b6d-518c87af543d.png)

**Comment by cannedit** [comment]
this ticket is added in Redmine as issue #46700
https://code.pictura-dp.nl/issues/46700
