### ISSUE TITLE
no notification for wrong password

### ISSUE THREAD

**Issue by wouteraddink** [DiSSCo/ELViS#30]
#### Description
if you try to login with a wrong password, you get no error message.

**Comment by cannedit** [comment]
I tried to reproduce this, but I got an error message (see screenshot attached); I agree that the message can be better specified: "email address and/or password is wrong" or something, but an error message is produced.
![image](https://user-images.githubusercontent.com/22167327/73252228-b5521780-41ba-11ea-83e2-61ad854f40fb.png)

**Comment by wouteraddink** [comment]
Strange, I don't get that message. Tested on both google chrome and ms explorer, so it seems not browser specific or browser cache related.

**Comment by cannedit** [comment]
You are right: you get the error message on the test server, but not on the acceptance server at the moment, so something went wrong with the deployment from test to acceptance; we will fix this

**Comment by cannedit** [comment]
this ticket is added in Redmine as issue #47170
https://code.pictura-dp.nl/issues/47170

**Comment by erzsebetgyongy** [comment]
I still get this error message (as above) even though I have put in the right password. I was logged in to Elvis but when I've logged out I couldn't log back in. I suppose I have to re-register again. ??

**Comment by cannedit** [comment]
@erzsebetgyongy yes: for each test run all registrations till so far are deleted, so you have to register again.
