### ISSUE TITLE
Q: Template for costs calculation

### ISSUE THREAD

**Issue by mnwdeboer** [DiSSCo/ELViS#34]
#### Question
Is there a template file (xls, doc) for the Cost section in the VA call form?
That a user (requester) can download. 

Form field -> Costs calculation (documents)

**Comment by wouteraddink** [comment]
I still not have the template despite several requests but I expect it this week. It will probably be an excel file. given the discussions about it, it will be simple and we might be able to replace it with a few fields in the form in the future.  There are some concerns about the number of files, if there are on average 10 files (10 institutes) involved per request and there are 100 requests, then it is already 1000 forms. To make processing voor the admin easier, it would help a lot if these are stored with harmonised names (I guess as file system not in the database?). For example requestID+instituteID (GRID)+institute abbreviation. That would make it possible to have automated processing and also it is human readable from which institute the file is.

**Comment by HMHardy** [comment]
Template coming today sorry. 
Ideas call suggests there will be fewer than 10 institutes per proposal (more like 2-6). 
Also Coordinators will have a key role in triaging requests to those that are feasible/appropriate, and will not want to complete too many cost templates - if each coordinator completes 10 templates (thus supporting 10 proposals, some of which overlap) that would only give 200 forms max.

**Comment by HMHardy** [comment]
The template is being shared with coordinators on Teamwork initially - do you want to include a link / instructions to find it there, or host it somewhere in ELViS? Either way, I think naming guidance would be helpful, happy to discuss and your suggestions seems sensible.

**Comment by cannedit** [comment]
I expect requesters to only upload one costs calculation document per institution, so given the fact that there are 19 institutions participating, theoretically there should only be 19 documents attached; in the form this functionality is positioned inside the info for one institution, so I will change the label from "Costs calculation (documents)" into: "Cost calculation (document)".
As for the link for the template for this document: that can be put somewhere in ELViS, for example on the info page for the VA Call, or (Plan B) on the page with info on the VA Call in the Synthesys+ website, for which the link is available on the info page for the VA Call in ELViS. In any case the text on the info page for the VA Call in ELViS should be adapted.

**Comment by HMHardy** [comment]
At present your list of institutions includes 20? I agree there are 19 on the Synthesys website but have not had time to check what's different so maybe worth a check.
I agree only one form per institution per proposal.

**Comment by cannedit** [comment]
Regarding the link for downloading the template for the Costs calculation document: I have just agreed with Wouter via a telephone conversation that the template will have to be put on the VA Call webpage of the Synthesys+ project, because - since apparently the requester is not the one to fill this in but the VA Coordinators - putting this up on the info page for the VA Call in ELViS will confuse requesters

**Comment by cannedit** [comment]
@HMHardy re: the issue of 19 or 20 institutions: the difference is that "Real Jardin Botanico de Madrid" is in our (20 institutions) list and that one was not in the list of the form for the preparation of the call and it is combined with "Museo Nacional de Ciencias Naturales" (both CSIC) on the webpage for the VA call in the Synthesys+ website; I understand from the email exchange about the costs calculation document we had yesterday with Scott Wilson that we will go for 20 institutions (so treating the CSIC institutions in Madrid as individual ones and I guess this means that we have to change the amount of institutions involved on the VA call info page in ELViS from 19 to 20?

**Comment by cannedit** [comment]
@HMHardy re: the issue of 19 or 20 institutions: @wouteraddink informed me it still has to be 19, because the two Spanish institutions belong to one project partner/beneficiary

**Comment by B-San-Chi** [comment]
That's right, the two institutions belong to the CSIC and go together on all Synthesys tasks. If it is a problem to join them, I can try to join them myself in a single template, but I don't know if this will arrive in time to be modified before the VA call

**Comment by cannedit** [comment]
@B-San-Chi no need to do this: the amount of institutions mentioned on the info page for the VA call will remain 19, but actually there will remain 20 institutions in the dropdown list for the requests, and Scott Wilson has adapted the costs calculation document in order to deal with the tow CSIC institutions, so this is already taken care of.

**Comment by B-San-Chi** [comment]
thanks
