### ISSUE TITLE
Registration interface lasts

### ISSUE THREAD

**Issue by mhirschfeld** [DiSSCo/ELViS#37]
#### Description
After filling out all fields of the registration and clicking the registration button, the registration interface lasts (filled out). If you click again on "Register" you receive registration. INCORRECT_PARAMETERS

#### Steps to reproduce the issue

1.  Registering a new user
2. 
3. 

#### What's the expected result?

- Registration interface should disappear with the notification of a successful registration

#### What's the actual result?

- Registration interface lasts with notifacation of a successful registration

**Comment by cannedit** [comment]
this ticket is added in Redmine as issue #46713
https://code.pictura-dp.nl/issues/47489

**Comment by wouteraddink** [comment]
![image](https://user-images.githubusercontent.com/395870/74428462-55fe3380-4e59-11ea-8033-efd45de79a8b.png)
