### ISSUE TITLE
Email login is case sensitive

### ISSUE THREAD

**Issue by HMHardy** [DiSSCo/ELViS#4]
#### Description

The login did not work when I typed my email 'h.hardy' because on the form I had put 'H.Hardy' by mistake - ideally it should not be case sensitive provided the email address is valid.

#### Steps to reproduce the issue

1.  enter an email address on registration form with one or more letters capitalised
2. Try to login with correct lowercase email
3. 

#### What's the expected result?

-

#### What's the actual result?

-

**Comment by cannedit** [comment]
this ticket is added in Redmine as issue #46701
https://code.pictura-dp.nl/issues/46701
