### ISSUE TITLE
Amend opening text

### ISSUE THREAD

**Issue by HMHardy** [DiSSCo/ELViS#42]
#### Description
On registration page, where it says 
'Proposers must contact relevant VA Coordinator(s) by 2 April. '
Please amend to 
'Proposers must contact relevant VA Coordinators as soon as possible, at the latest by 2 April'
Thanks!

#### Steps to reproduce the issue

1.  
2. 
3. 

#### What's the expected result?

-

#### What's the actual result?

-

**Comment by HMHardy** [comment]
Apologies I now notice this is linked to issue #32

**Comment by cannedit** [comment]
Registered as Redmine issue: 47502
https://code.pictura-dp.nl/issues/47502
