### ISSUE TITLE
Impact page - typo and overall position in form

### ISSUE THREAD

**Issue by HMHardy** [DiSSCo/ELViS#46]
#### Description
You have a typo:
'Who do you expect to be the users of the data (please include all **rows**, not just scientific research users)? ' - instead of rows should say groups

I wonder if the impact section should come as the second page in the form, since it reflects the abstract and is the overall case for the proposal? Beyond this the proposers will have to get more content from the coordinators so it may make more sense to complete this first? This is not critical however.

#### Steps to reproduce the issue

1.  
2. 
3. 

#### What's the expected result?

-

#### What's the actual result?

-

**Comment by cannedit** [comment]
We will take care of the text change: "rows" will be replaced with "groups"

Registered as Redmine ticket: 47508
https://code.pictura-dp.nl/issues/47508
