### ISSUE TITLE
Text for end of form (submission etc)

### ISSUE THREAD

**Issue by HMHardy** [DiSSCo/ELViS#47]
#### Description
Currently the final page of the form only invites submission.
This should offer a choice - e.g. save for editing, or to submit? And text should be clear that forms cannot be amended after submission.

I see that at present forms can be viewed after submission - will this be true for all requests and all requestors/coordinators etc registered on ELViS? If so this page should say where you can view the proposal after submission. Otherwise it would be helpful to offer e.g. a copy or link via email, or text saying that it will not be possible to view and offering e.g. a download copy? 

#### Steps to reproduce the issue

1.  
2. 
3. 

#### What's the expected result?

-

#### What's the actual result?

-

**Comment by cannedit** [comment]
See the info in Github https://github.com/DiSSCo/ELViS/issues/35

Submit/submission is: saving the version for VA Coordinators to evaluate; after that - for now (MVP ELViS) only the original requester can change the request, nobody else; the idea is then that the VA Coordinators communicate with the requesters via a comments system, so VA Coordinators should indicate via that system to the requesters what they should change/add; when this communication is finished to the satisfaction of each VA Coordinator involved, then each VA Coordinator can approve (or reject) his/her part of the request and if all VA Coordinators involved have approved their part, then the request is accepted; but this whole functionality is not in place yet, we're working on that right now.

Furthermore it's the idea that at the end of a submission an overview on screen plus a PDF of the submitted request will be available.

**Comment by HMHardy** [comment]
Ah ok - I assume wording will reflect that? Otherwise the natural assumption is that 'submit' is tthe final submission to the centre.
The final submission page after coordinator comments etc will need to reflect points above anyway?

**Comment by cannedit** [comment]
Yes, we will probably change that once the above described functionality is in place

**Comment by wouteraddink** [comment]
Suggestion to change the wording to:  "Are you sure everything is done?
Then submit the request to publish as draft." And then change on the requests  overview page http://elvis-accept.pictura-hosting.nl/requests the status description "draft" into "incomplete" and "submitted" into "draft". 

This is the smallest change I can think of to make it clear for the user.

**Comment by HMHardy** [comment]
Sorry Wouter I don't think that text quite captures what is said above. 
The text needs to specify exactly what will happen e.g. 'click submit to publish the request as draft so that VA coordinators can see it [and comment??] [- only you will be able to amend and submit the final draft]' Or whatever similar wording accurately represents the process in full.
This is because ELViS has effectively introduced a new process for collaboration on the form, which is not currently covered in the guidance, so there needs to be zero room for confusion on this page if possible?

**Comment by cannedit** [comment]
We will take care of a suitable text on the last page, but we are already taking care of informing the requester in another way about the process for example via a blue 'sticky note' to the right of the form (sticky as in: available on every page and moving along with scrolling down), which also has the possibility to be expanded (via the link "more info"):
![ELViS_RequestFormInfo](https://user-images.githubusercontent.com/22167327/74566029-d95f7800-4f72-11ea-9830-17f2b6e52ae2.png)

This is already implemented in the version which will be offered for test on Monday.

**Comment by cannedit** [comment]
For definitive text to be put on the last page of the request form see Github issue https://github.com/DiSSCo/ELViS/issues/47
