### ISSUE TITLE
Navigation heading 'requesters' may not be clear

### ISSUE THREAD

**Issue by HMHardy** [DiSSCo/ELViS#5]
#### Description

I am not sure it is clear having a tab for 'requesters' as well as for 'requests'? But it's hard to tell at this stage. Feels like this might need to be a tab for 'people'? or will there be multiple role tabs? Sorry more of a question than an issue.

#### Steps to reproduce the issue

1.  
2. 
3. 

#### What's the expected result?

-

#### What's the actual result?

-

**Comment by wouteraddink** [comment]
Requesters are the people requesting access and requests are the access requests themselves. I think this will become more clear during implementation.
