### ISSUE TITLE
ORCiD field in registration form needs more info

### ISSUE THREAD

**Issue by wouteraddink** [DiSSCo/ELViS#50]
#### Description
in the registration field, the ORCiD info icon only displays the format for an ORCiD which is not very helpful. Some people might not know what and ORCiD is, that should be explained here.
Proposal: change with text: 

The ORCiD is a  code to uniquely identify people that create, add to, or use scientific material. You can get an ORCiD for free here: https://orcid.org. We require this as we want to connect results from the virtual access with people and publications in the future.

**Comment by cannedit** [comment]
Registered in Redmine as issue: 47526
https://code.pictura-dp.nl/issues/47526
