### ISSUE TITLE
enhancements to requests overview page 

### ISSUE THREAD

**Issue by wouteraddink** [DiSSCo/ELViS#51]
#### Description
At some point the requests page http://elvis-accept.pictura-hosting.nl/requests needs to show the request identifiers (can be as mouse-over on the title). I would also suggest to remove the arrows and make the change in color for a row when you hover over it more visible. That will indicate that you can click on it to go to the details.

**Comment by AnniinaK** [comment]
Same problem with the arrows on other pages. Should the arrows be removed from all the pages listing items (institutions, requesters, calls, requests)? And instead make the change in colour more visible if the row can be clicked? Now for the Institutions page, when hovering over the arrow, the mouse cursor changes to a hand but you can't click the arrow. On the Requesters page mouse cursor does not change and you can't click the arrow. 

(Sorry if this would have been better as a separate issue)

**Comment by wouteraddink** [comment]
I agree, this should become consistent in the future.

**Comment by cannedit** [comment]
This is solved but in another way:
- for Requesters the arrow is changed into info on whether a requester account is still active/valid
- for Institutions the whole bar with info (including the arrow) is now clickable
