### ISSUE TITLE
In the Create New Request - if you have already selected an institute (i.e. RBGE) for the VA call, will there be a drop down lists in the Collection Name and Preservation Type fields which relate to specific collections?  At the moment it is all free text.

### ISSUE THREAD

**Issue by LesleyScott** [DiSSCo/ELViS#53]
#### Steps to reproduce the issue

1.  
2. 
3. 

#### What's the expected result?

-

#### What's the actual result?

-

**Comment by wouteraddink** [comment]
Yes, but this can only be provided once we have received and processed this information from all the VA institutes. At the moment we are still missing information so this will have to be implemented after the opening of the call.
