### ISSUE TITLE
Not intuitive how to make a new request

### ISSUE THREAD

**Issue by wouteraddink** [DiSSCo/ELViS#56]
#### Description
After login you are directed to an empty dashboard page. It is not intuitive how to submit a new proposal (make a request) from here. You cannot find a [new request] button on the requests page. Only if you go to the call detail page you will find it. For the MVC I would suggest to 

1. add a button [new request] on the request page that links to http://elvis-accept.pictura-hosting.nl/calls/7d4cc4af-ac72-406e-b128-0edb23e48659. This is a temporary solution, later the button should be replaced by functionality to make a new request of certain type, and for VA or TA include selecting one of the open calls.
2. modify the call text on that page to "Use the Create New Request button on this page to create your proposal for a Digitisation on Demand request. 19 SYNTHESYS+ partners are preparing..."

**Comment by cannedit** [comment]
Registered as Redmine issue: 47535
https://code.pictura-dp.nl/issues/47535
