### ISSUE TITLE
empty pages

### ISSUE THREAD

**Issue by wouteraddink** [DiSSCo/ELViS#57]
#### Description
After login you end up with an empty dashboard page. It would be more user friendly to either be redirected to http://elvis-accept.pictura-hosting.nl/calls after login, or to provide the text from the welcome page again. The empty collections and facilities pages could either be not avaible (greyed out buttons) or showing a text like 
"Collections 
(this functionality will be implemented later in 2020)".

**Comment by cannedit** [comment]
Registered as Redmine issue: 47535
https://code.pictura-dp.nl/issues/47535
