### ISSUE TITLE
Time of request on Requests page

### ISSUE THREAD

**Issue by AnniinaK** [DiSSCo/ELViS#58]
#### Description
On the Requests list, in the column "Request date" also time is displayed but it shows 00:00:00 for all requests. If the time is not stored at all, should display only date and not date + time. And if time should be stored, is there something wrong?

#### Steps to reproduce the issue

1.  Go to Requests
2. See time in column Request date
3. 

#### What's the expected result?

Show correct time or no time at all.

#### What's the actual result?

Shows 00:00:00 for all requests.

#### Additional details / screenshot

![image](https://user-images.githubusercontent.com/58849512/74541583-8d98d880-4f4a-11ea-8f0d-b8b04882bba6.png)

**Comment by cannedit** [comment]
Will be taken care of (already recognised by us and already fixed the the version which will be up for testing on Monday)
