### ISSUE TITLE
Plus button does not always function on the request form

### ISSUE THREAD

**Issue by AnniinaK** [DiSSCo/ELViS#59]
#### Description
When typing in a content to a field and clicking the plus (to add e.g. another collection) without first moving the cursor to another field or clicking outside the field, new section is not added. Seems to be related to the automatic saving somehow. Apparently automatic saving is done once you leave a field, meaning move the cursor out from the field?

#### Steps to reproduce the issue

1. Go to add a new request, give subject and move to next
2. Choose an institution
3. Type in a collection name and leave the cursor there (do not click outside the field or to another field)
4. Click plus button

#### What's the expected result?

Fields to fill in details for another collection should appear

#### What's the actual result?

New section/fields do not appear (sometimes flash there quickly)

#### Additional details / screenshot

I did not manage to reproduce this 100% of times but mostly. So maybe still something I don't notice that affects it.  Tested on Firefox Quantum 68.5.0esr (64-bit)

**Comment by cannedit** [comment]
Will be taken care of (already recognised by us and already fixed the the version which will be up for testing on Monday); in addition: deleting an added section causes a problem at the moment too (which can be solved for now by clicking back and forth via the "next" and "previous" buttons at the bottom of the page), but that will be taken care of too.

**Comment by mtrekels** [comment]
When adding e.g. a collection, I need to click the '+' button twice before the new entry field appear

**Comment by AnniinaK** [comment]
Yes this does not seem to fixed yet, same steps still cause the issue.

**Comment by wouteraddink** [comment]
I think this issue still exist, if I try to add a second facility or data storage I still need to click twice

**Comment by cannedit** [comment]
I wasn't able to reproduce this at my end, using Chrome and Firefox this works fine, multiple times, so I only have to click once; maybe this was caused at your end by hickups of the internet connection, so please try to reproduce this again.

**Comment by wouteraddink** [comment]
looks like this issue still exist. I can add multiple collections, but if I enter something in the second and want to add a third, I have to click twice. Only happens if I enter something in one of the collection fields and seems to be happening from second one onwards. I can add multiple empty ones without having this problem. I was also a little confused by the minus button, to which collection it refers to as it is positioned in between two collections and that when I click it, the collection is deleted rather than collapsed (but that is intended behaviour. A trashbin icon may be more clear.)

**Comment by mtrekels** [comment]
Same happens for me

**Comment by cannedit** [comment]
I am sorry, but I still can't reproduce this, see the video attached.
[TestingELViS_CollectionsFaciltiesRepeatableFields.zip](https://github.com/DiSSCo/ELViS/files/4819459/TestingELViS_CollectionsFaciltiesRepeatableFields.zip)

It might have something to do with internet connection speed and the real time storage of values that are put in the fields, especially when only producing extra empty fields doesn't seem to have this problem.

**Comment by scottwilson-nhm** [comment]
After testing, I only have to click once here. My internet speed is what I assume is 'normal' for the UK countryside... (2ms Ping; 5.93 mbps download; 1.41 mbps upload). But looking through this thread it seems like others are having an issue?
