### ISSUE TITLE
Registration fails: "Incorrect parameters"

### ISSUE THREAD

**Issue by AnniinaK** [DiSSCo/ELViS#6]
#### Description
Registration fails and an error message "Incorrect parameters" is given. None of the fields are highlighted in red. Filled in Name (highlighted green), Surname (green), Email (green), Password (no colour) and Repeat password (no colour). ORCiD was empty (no colour). I suspect the password may have been too long (33 characters, both upper case and lower case, numbers, no special or Scandinavian characters) because when I changed the password to a shorter one (15 characters) the registration was successful.

#### Steps to reproduce the issue

1.  Fill in Name, Surname, Email, Password, Repeat password (with password 33ch)
2. Click Register

#### What's the expected result?

Successful registration or a more informative error message.

#### What's the actual result?

Error message "Incorrect parameters" and registration fails.

#### Additional details / screenshot
![Elvis_registeration_incorrect_parameters](https://user-images.githubusercontent.com/58849512/71578179-c1857f00-2aff-11ea-812c-84223976f0d0.jpg)

**Comment by wouteraddink** [comment]
This seems to occur if the password entered was too short. The error message should be more informative, the password fields should be red and password field needs an help text to state the requirments.

**Comment by cannedit** [comment]
this ticket is added in Redmine as issue #46704
https://code.pictura-dp.nl/issues/46704
