### ISSUE TITLE
Strange behaviour on the request form when adding and removing repeatable elements

### ISSUE THREAD

**Issue by AnniinaK** [DiSSCo/ELViS#60]
#### Description
Adding and removing repeatable elements does not seem to work properly. Previously added and later removed collections (for example) reappear when adding a new collection. Perhaps somehow related to the automatic saving? I tested with the sections "Collection(s) involved" and "Facilities and workflow" on the "Institutions involved" part of the form. 

(I am assuming the minus button is supposed to remove an element and not just hide it somehow?)

#### Steps to reproduce the issue

1. Go to add a new request, give subject and move to next
2. Choose an institution
3. Type in a collection name, for example "Collection 1"
4. Add another collection using the plus button, name it "Collection 2"
5. Add a third collection using the plus button, name it "Collection 3"
6. Remove "Collection 2" and "Collection 3" using the minus buttons
7. Add a new collection using the plus button
8. Click to the collection name field (that is empty at this stage), don't write anything
9. Click outside the form

(Collection as an example in the steps but same happens with at least "Facilities and workflow", I did not test other repeatable elements)

#### What's the expected result?

Only "Collection 1" should be on the form + an empty collection element.

#### What's the actual result?

"Collection 2" and "Collection 3" appear back on the form.

#### Additional details / screenshot
Tested on Firefox Quantum 68.5.0esr (64-bit)

**Comment by cannedit** [comment]
See my remark in Github issue https://github.com/DiSSCo/ELViS/issues/59

**Comment by vixriihi** [comment]
This still happens in "Facilities and workflow" -section and in "Data storage and release" -section
