### ISSUE TITLE
Improve typing of ORCiD on the registration form

### ISSUE THREAD

**Issue by AnniinaK** [DiSSCo/ELViS#61]
#### Description
Minor enhancement I think, but when typing ORCiD on the registration form, cursor could automatically move to the next one of the id fields once you have typed four characters to a field, instead of having to move the cursor manually. Also could display the dashes between the fields to highlight the correct format.

**Comment by cannedit** [comment]
This is already reported in Github issue https://github.com/DiSSCo/ELViS/issues/9

Already taken care of in the version which will be up for testing on Monday
