### ISSUE TITLE
email received to approve draft request

### ISSUE THREAD

**Issue by wouteraddink** [DiSSCo/ELViS#63]
#### Description
I got the following email today. I went to the Elvis system but I can't accept the requests. They are in draft stage and when I try to submit the request it gets stuck and won't go anywhere. What should I do?

Best
Anne

-----Original Message-----
From: noreply@elvis-accept.pictura-hosting.nl <noreply@elvis-accept.pictura-hosting.nl>
Sent: keskiviikko 19. helmikuuta 2020 10.35
To: Koivunen, Anne M <anne.koivunen@helsinki.fi>
Subject: A new VA request for your Institution has been created in ELViS

Dear Anne Koivunen,

In the European Loans and Visits system (ELViS) a new VA request for the institution “Helsingin Yliopisto, Finnish Museum of Natural History” for which you are VA Coordinator has been submitted Please go to: elvis-accept.pictura-hosting.nl/requests/17a0c83a-4994-4f8a-8d4e-ece1ec75b552 to evaluate this request.

Best wishes,
Administrator name}
Administrator European Loans and Visits system (ELViS)

#### What's the expected result?
To get these emails only for requests that have been submitted for review by the VA coord

#### What's the actual result?
get these for a draft request.

**Comment by B-San-Chi** [comment]
I have also receive this email, I went to the Elvis system but I can't read the requests. There is no text and when I try to send the application it gets stuck. What should I do?

**Comment by B-San-Chi** [comment]
I have tried to upload a document with a cost estimate, the file is uploaded correctly but when I click on the approve button it is also blocked

**Comment by cannedit** [comment]
@B-San-Chi for approving requests for which you received an email notification, you should log in as VA coordinator, using the login details Wouter has provided you; it is possible that you for now also receive email notifications in case a draft request is registered for your institution, but this is a known bug and we're working on solving this: as VA coordinator you should only get email notifications for requests which are submitted and as VA coordinator you should NOT see any requests which are still in draft (which is the case at the moment) 

As for uploading a document: we are working on this too at the moment, but this will probably not be fixed before the deadline (tomorrow), but during a 'hotfix' deploy shortly after the deadline; for the deadline we concentrate on getting the registration of request optimised as much as possible.

**Comment by B-San-Chi** [comment]
Yes, that's what I did, using the password sent by Wouter. Thanks

**Comment by cannedit** [comment]
Registered as Redmine issue: 47581
https://code.pictura-dp.nl/issues/47581
