### ISSUE TITLE
Format of license

### ISSUE THREAD

**Issue by mtrekels** [DiSSCo/ELViS#64]
#### Description
When you have to pick the license:
- 'CC' should be capitals?
- Don't we have to specify the version of the licence? E.g. CC-BY-SA-3.0

**Comment by cannedit** [comment]
it was decided to only use 
- CC0 - https://creativecommons.org/publicdomain/zero/1.0/
- CC-BY - https://creativecommons.org/licenses/by/4.0

I will ask the team to use capitals

Registered as Redmine ticket: 47615
https://code.pictura-dp.nl/issues/47615

**Comment by wouteraddink** [comment]
I think License type needs an info icon for more info.
suggestion: 
CC stands for Creative Commons license.  For CC0 see: https://creativecommons.org/publicdomain/zero/1.0/ and for
CC-BY see: https://creativecommons.org/licenses/by/4.0.
Only non-restrictive licensing is permitted in the Virtual Access calls. Non-commercial and Share-Alike licences are restrictive in practice and therefore not permitted.
