### ISSUE TITLE
VA coordinator can submit draft request

### ISSUE THREAD

**Issue by mtrekels** [DiSSCo/ELViS#65]
#### Description

In the requests, I have in my overview a draft request. As a VA coordinator I can modify and submit this request. This seems to be unexpected behavior.

Also, In the overview, the status is 'draft'. While this seems to be 'submitted' when I open the request. See screenshots.

<img width="703" alt="draft_1" src="https://user-images.githubusercontent.com/52746754/74825130-b08c0980-5309-11ea-84b4-61140e150981.png">
<img width="733" alt="draft_2" src="https://user-images.githubusercontent.com/52746754/74825131-b1bd3680-5309-11ea-8d5b-7565c11b8463.png">
<img width="672" alt="draft_3" src="https://user-images.githubusercontent.com/52746754/74825133-b1bd3680-5309-11ea-82ef-8878b3d87cf3.png">

**Comment by mtrekels** [comment]
Extra information: list of draft request is getting larger, but clicking on one brings me always to the same request

**Comment by cannedit** [comment]
this bug is already recognised and we're working on solving this; VA coordinators are not supposed to see draft requests, only submitted requests; will be solved before we go 'live' tomorrow

Registered as Remine issue: 47581
https://code.pictura-dp.nl/issues/47581

**Comment by AnniinaK** [comment]
> 
> 
> Extra information: list of draft request is getting larger, but clicking on one brings me always to the same request

This same thing happens for Anne here too, VA coordinator can't navigate between requests now.
