### ISSUE TITLE
Map of location of institutes

### ISSUE THREAD

**Issue by mtrekels** [DiSSCo/ELViS#66]
#### Description

I noticed that the map that is displayed on the institutions pages, is showing the center of the city and not the institute address.

It is also only possible to use the map with + and - signs of the keyboard. No mouse navigation is possible (Google Chrome)

**Comment by cannedit** [comment]
Registered as Redmine issue: 47615
https://code.pictura-dp.nl/issues/47615

**Comment by mnwdeboer** [comment]
I have understood that the information of an institute comes from CETAF.
