### ISSUE TITLE
Delete/minus buttons missing on the form

### ISSUE THREAD

**Issue by AnniinaK** [DiSSCo/ELViS#67]
#### Description
Minus buttons to remove repeatable sections are missing from the form, institutions and collections part. There is only one minus button on the last element.

#### What's the expected result?

Would expect to be able to delete any element, regardless of the order where they were added.

#### What's the actual result?

Can only delete starting from the last element.

#### Additional details / screenshot
![image](https://user-images.githubusercontent.com/58849512/74830540-0d90bb00-531c-11ea-8181-0a07a2b87a87.png)

**Comment by cannedit** [comment]
We had a minus field per element set up and running, but that somehow broke the form, so this will be taken care of after the MVP ELViS deadline

**Comment by cannedit** [comment]
The repeatable sections have been improved, so this will probably not occur anymore
