### ISSUE TITLE
Empty repeatable sections disappear

### ISSUE THREAD

**Issue by AnniinaK** [DiSSCo/ELViS#68]
#### Description
When adding new repeatable sections in a row, the ones that don't have content yet, disappear on the form. No data gets lost and this can be avoided by adding and typing content one collection at a time, so this is not crucial I think but future enhancement?

#### Steps to reproduce the issue

1.  On the institutions and collections part of the form, add for example four new collection elements in a row, don't write any content yet
2. Write a name for the first collection
3. move to another field

#### What's the expected result?
All previously added elements to remain on the form

#### What's the actual result?
Empty elements (that do not have content yet) disappear

**Comment by cannedit** [comment]
The repeatable sections have been improved, so this will probably not occur anymore

**Comment by HMHardy** [comment]
I have tried to replicate this and couldn't so may be resolved, but I wasn't quite clear - I added two institutes and some collections info, could not see that anything disappears, although while working on one institute the other is condensed which seems sensible.

**Comment by AnniinaK** [comment]
For me the original thing still happens. The issue is when working within one institute, when adding more than one "collection involved" or "facilities and workflow" or "Data storage and release". (Not with multiple institutes disappearing.)

Also new, related thing I noticed: add for example four new empty "collections involved" -sections, try to delete one of them using the minus button --> all the empty sections disappear.

**Comment by cannedit** [comment]
I think this is expected behavior because of the 'real time' storing of data 'on the fly', so I think for empty fields or fields sets this is Ok, but if it also occurs when fields or fields sets already have data in it, then it would be a problem and I haven't seen that happening anymore lately

**Comment by AnniinaK** [comment]
Yes, I agree it is not a big problem as no data gets lost and can be avoided doing things in a different order (like written in the original description). Just a bit counter-intuitive behaviour anyway.
