### ISSUE TITLE
Platform for public data release info icon

### ISSUE THREAD

**Issue by wouteraddink** [DiSSCo/ELViS#69]
#### Description
Platform for public data release (data storage and release section) should have an info icon with the following guidance:
Data   release   should   be   on   established   institutional   or   global   platforms   with longevity,   e.g.   GBIF,   Zenodo,   GenBank.   Data   release   cannot   be   via   citizen   science platforms (although they could be used to serve data for uses subsequent to VA projects).

**Comment by cannedit** [comment]
Registered as Redmine issue: 47638
https://code.pictura-dp.nl/issues/47638
