### ISSUE TITLE
improve error message on duplicate registration

### ISSUE THREAD

**Issue by wouteraddink** [DiSSCo/ELViS#7]
#### Description
when trying to register with an already registered email address, you get the error message 
User with the specified address already exists

#### Steps to reproduce the issue

1.  try to register with an already registered email address

#### What's the expected result?
error message: User with the specified **email** address already exists

#### What's the actual result?

error message: User with the specified address already exists

**Comment by cannedit** [comment]
this ticket is added in Redmine as issue #46711
https://code.pictura-dp.nl/issues/46711
