### ISSUE TITLE
Proposed timeline for data release info icon

### ISSUE THREAD

**Issue by wouteraddink** [DiSSCo/ELViS#70]
#### Description

**proposed timeline for data release** should have an info icon with the folowing text:

Data release should take place as projects proceed, or at the latest immediately after completion- reasons for longer timescales should be clearly stated. It is unlikely that projects will be prioritised if data release is subject to legal or other compliance restrictions (e.g. human remains), or is dependent on work outside the scope of the funded project (e.g. would not be released until substantial further work is undertaken).

**Comment by cannedit** [comment]
Registered as Redmine issue: 47637
https://code.pictura-dp.nl/issues/47637
