### ISSUE TITLE
make more clear what submission means

### ISSUE THREAD

**Issue by wouteraddink** [DiSSCo/ELViS#73]
#### Description
suggestion to replace the text:
 Are you sure everything is done?
Then make the request.

with:
Is your request ready to be made public? If you submit than your request will become available for the VA coordinators to comment on and to approve.  This is NOT yet the final submission. This stage will also allow other institutes or requesters to suggest their involvement in your proposal. You can do a final submission for peer review after all VA coordinators from the digitising institutes involved have approved your request.

**Comment by cannedit** [comment]
Registered as Redmine issue: 47615
https://code.pictura-dp.nl/issues/47634
