### ISSUE TITLE
change institute name

### ISSUE THREAD

**Issue by wouteraddink** [DiSSCo/ELViS#75]
#### Description
would it be possible to change our institution name in Elvis at some point from “Helsingin Yliopisto, Finnish Museum of Natural History” to “Finnish Museum of Natural History, University of Helsinki”. This way it would be more logical, more easy to find and does not mix two languages. We know this is a very minor detail in the big picture, but we just thought we’d ask. Did not feel this is worth a github issue though.

Kind regards,
Anniina Kuusijärvi

**Comment by mnwdeboer** [comment]
Redmine issue #47743 (priority:low)

**Comment by wouteraddink** [comment]
Not fixed, it now has a typo:

HFinnish Museum of Natural History, University of Helsinki

**Comment by cannedit** [comment]
Registered as Redmine ticket: 47743
https://code.pictura-dp.nl/issues/47743

**Comment by cannedit** [comment]
It has been corrected on the Production server.
