### ISSUE TITLE
representation of ORCID iD

### ISSUE THREAD

**Issue by wouteraddink** [DiSSCo/ELViS#78]
#### Description
Currently we refer to ORCID iDs as ORCiDs (and as ORCid in the "request by" sticky note next to the VA webform, which is a typo) . According to the https://orcid.org/trademark-and-id-display-guidelines we should not do this, but either use the iD icon or use the term ORCID iD. 

suggestion to replace ORCiD on the registration form with ORCID iD and anywhere else to use the icon.

**Comment by emhaston** [comment]
We also need to standardise the ORCID iDs so that we are using either the digit or the url but not a mixture.

**Comment by cannedit** [comment]
Registered in Redmine as Issue: 49054
https://code.pictura-dp.nl/issues/49054
