### ISSUE TITLE
type and number validation

### ISSUE THREAD

**Issue by wouteraddink** [DiSSCo/ELViS#79]
#### Description
There is a typo in the VA webform: "Number of specimen to digitise" should be "Number of specimens to digitise", and the field should have number validation, now you can fill in text.

**Comment by mnwdeboer** [comment]
I created a issue for this in redmine #15625

**Comment by wouteraddink** [comment]
resolved, but I dont understand why the field now has arrows if you fill it in

**Comment by cannedit** [comment]
that is for increasing and decreasing a number more easily; in addition: I have found out that you can still put in text, so like "15 or more", but upon leaving the request and returning to it, then the whole input has disappeared; so this needs some rework (Redmine issue 47741 https://code.pictura-dp.nl/issues/47741)

**Comment by AnniinaK** [comment]
Also noticed, that with the down arrow, it is possible to go to negative numbers, below zero. Decreasing a number should stop at zero?
