### ISSUE TITLE
map on welcome page needs to be changed

### ISSUE THREAD

**Issue by wouteraddink** [DiSSCo/ELViS#81]
#### Description

The map on the ELViS opening screen has issues:

- it shows Yugoslavia! That country disintegrated almost 30 years ago!
- It lacks both Germany’s and Sweden’s largest islands (Rügen and Gotland)
- It shows boundaries within the UK (which it doesn’t show for any other country)
- The Russian enclave of Kaliningrad between Latvia and Poland is missing
- The Aegean Sea, Black Sea, and the Dardanelles between them are essentially shown as countries, not water bodies

**Comment by mnwdeboer** [comment]
Found a more recent vector map of Europe. So I made some changes and updated the image.
