### ISSUE TITLE
change in VA coordinator Vienna

### ISSUE THREAD

**Issue by wouteraddink** [DiSSCo/ELViS#82]
#### Description
change in VA coordinator
The VA coordinator from NHM Vienna changed from Nora Wurzinger to Maria Marschler, synthesys@nhm-wien.ac.at. Nora will not respond to emails from ELViS, so this needs to be changed quickly.

**Comment by cannedit** [comment]
Registered as Redmine ticket 47808
https://code.pictura-dp.nl/issues/47808

**Comment by cannedit** [comment]
The VA Coordinator change has been deployed
