### ISSUE TITLE
change in VA coordinator Senckenberg

### ISSUE THREAD

**Issue by wouteraddink** [DiSSCo/ELViS#83]
#### Description
The VA coordinatro for Senckenberg changed from Marco Thines to: tobias.schneck@senckenberg.de. Marco will not answer emails coming from ELViS so this needs to be changed quickly.

**Comment by cannedit** [comment]
Registered as Redmine ticket 47808
https://code.pictura-dp.nl/issues/47808

**Comment by cannedit** [comment]
The VA Coordinator change has been deployed

**Comment by wouteraddink** [comment]
I assume that password stayed the same, so I sent the same password to the new person

**Comment by cannedit** [comment]
No, that's not the case: new VA Coordinator gets new password; I already informed Tobias about it; problem is that request already entered for the old VA Coordinator don't get automatically assigned to the new one, we're sorting that out now. So for now - untill VA Coordinator role is fully implemented and profile pages allow to change email addresses and passwords - changing a VA Coordinator is a bit complicated and should be avoided. Fortunately for the other institution which had a VA Coordinator change there was now request registered for the old VA Coordinator yet.
