### ISSUE TITLE
Improve position of the button to add more institutes

### ISSUE THREAD

**Issue by wouteraddink** [DiSSCo/ELViS#85]
#### Description

In the second section of the VA form (“Institutions & Collections”), the button to add a new institute is actually at the bottom of the previous institute, this is no problem as long as you do not move to another page, but when you do and come back later all institute forms will be displayed as closed.
so you need to open the last one you see in your list of selected institutes and then you see the button. This is not intuitive and some people cannot find the button.

**Comment by HMHardy** [comment]
So far as I can see having tried to replicate this it is now resolved - the form stays open with the button at the bottom even when I have gone back or forward a page

**Comment by HMHardy** [comment]
Oh, but now when I click the button to add the next institute it closes the first institute but then I have to click the button again before the drop down appears - this is odd?

**Comment by mtrekels** [comment]
I observe the same behavior.

**Comment by cannedit** [comment]
That's not the behavior I see: there is no need to click the "add" button again, after clicking it, the previous institute info collapses and then you can immediately select another institution from the dropdown list, at least in Firefox (see the screenshot attached) 
![ELViS_AddingAnotherInstitution](https://user-images.githubusercontent.com/22167327/76623600-14ce7180-6534-11ea-8ddf-f5dbe9f3dc90.png)

**Comment by mtrekels** [comment]
I re-tested this on Firefox and Chrome: you are right, the confusing part is that it jumps to the top of the screen and you need to scroll down to continue

**Comment by mtrekels** [comment]
There seems to be still an issue though when adding an extra collection within an institute. There I need to click the '+' button twice

**Comment by cannedit** [comment]
I can't reproduce that behavior, and unfortunately I can't upload a video on Github to show you.
