### ISSUE TITLE
After submission, the requester can't modify request anymore

### ISSUE THREAD

**Issue by mtrekels** [DiSSCo/ELViS#86]
#### Description
After submission, the VA coordinator can comment on the request. However, the requester can't change the request to incorporate the remark

#### Steps to reproduce the issue

1.  requester submits request
2.  requester tries to edit the request

#### What's the expected result?

- requester should be able to incorporate the remarks of the VA coordinator

#### What's the actual result?
nobody can adjust the request; only comment on it

**Comment by cannedit** [comment]
Registered in Redmine as issue: 
https://code.pictura-dp.nl/issues/48020

**Comment by emhaston** [comment]
I tried to edit a request to add an additional collection but couldn't so this functionality would be useful.

**Comment by HMHardy** [comment]
This is fundamental to how the process is supposed to work so hopefully being prioritised? It might be helpful if Github showed some indicator of priority of issue backlog?

**Comment by B-San-Chi** [comment]
As a VA coordinator I can not edit the request to change or add somethig and I try to upload the template with the cost calculation but it keeps "thinking"

**Comment by B-San-Chi** [comment]
Ok! after 1hour, the file is uploaded

**Comment by cannedit** [comment]
@HMHardy this is recognised and prioritised as most important issue before deployment to production next week.
@B-San-Chi for the uploading of a cost calculation document we have another ticket; but this uploading should not take that long, I have tested it a lot lately in it's there within a few minutes, so please try again?

**Comment by B-San-Chi** [comment]
Ok, now the uploading file was inmediatly. But now, the green button for the approval keeps thinking

**Comment by cannedit** [comment]
I guess that's due to the fact that there is a lot of testing going on at the moment on the acceptance server; the performance of the production server will be better.

**Comment by mtrekels** [comment]
Tested the workflow: OK
