### ISSUE TITLE
No clear way to close login dialog

### ISSUE THREAD

**Issue by vixriihi** [DiSSCo/ELViS#87]
#### Description

If you acidetly open login dialog. There is no clear way to close it. For example if I was planning to register but instead accidently clicked login I cannot close the opened dialog.

#### Steps to reproduce the issue

1.  Click login

#### What's the expected result?

- Login dialog would have close icon and/or that clicking backdrop would close it and/or pressing esc key would close it.

#### What's the actual result?

- Login dialog is open but no clear way to close it (browsers back button seems to be now the only way to close it)

#### Additional details / screenshot

Close button in login dialog seems to be present in https://elvis.dissco.eu/
but not in http://elvis-accept.pictura-hosting.nl/

**Comment by cannedit** [comment]
Registered as Redmine issue: 48046
https://code.pictura-dp.nl/issues/48046

**Comment by HMHardy** [comment]
This still seems to be an issue - I tried to login and requested password reset, now I am stuck with the dialogue box

**Comment by cannedit** [comment]
@HMHardy yes, this is recognised as a bug, but after the latest deployment on Acceptance, so it will be fixed during the next round

**Comment by cannedit** [comment]
We didn't provide a "close" button, but a possibility to go to the registration page again.
