### ISSUE TITLE
ORCID field not correctly validated

### ISSUE THREAD

**Issue by wouteraddink** [DiSSCo/ELViS#9]
#### Description
There is no validation for the ORCID field in the registration form

#### Steps to reproduce the issue

1.  enter any text in the ORCID field that is not an ORCID
2. 
3. 

#### What's the expected result?
Should at least validate the format: 0000-0000-0000-0000
preferrably should help with the format making the separation in 4 digit parts.
preferrably should check with ORCID API if the ORCID exist and if so, fill in the first name and last name from the ORCID information, so the user does not need to repeat that on the registartion form

#### What's the actual result?
can enter anything

**Comment by cannedit** [comment]
this ticket is added in Redmine as issue #46713
https://code.pictura-dp.nl/issues/46713

**Comment by Karin-Wiltschke** [comment]
if you put in the ORCID number it doesn`t jump to the next four Digit block, you have to use the mouse to enter the next digits, this a Little bit anoying

**Comment by cannedit** [comment]
We will take care of this; registered as Redmine ticket: https://code.pictura-dp.nl/issues/47487

**Comment by AnniinaK** [comment]
Has improved, but I assume check from ORCiD API is to be done later? At least one can still use 1234-1234-1234-1234 for example.

**Comment by cannedit** [comment]
Yes, the real ORCID validation is for the next development phase, however, we have identified that an ORCID can also consist of characters (for example an "X" as the last digit of the fourth block, so we're going to enable that as well for the MVP ELViS

**Comment by wouteraddink** [comment]
yes, will need further improvement in the future.

**Comment by wouteraddink** [comment]
I have a little complication for you: I tried to register into Elvis proto and it refused my ORCID  number. Probably because it ends with an X ! The last digit is a checksum that goes from 0 to 10 (X). You could try it : https://orcid.org/0000-0002-7104-898X

Sincerely,

 Pierre-Yves GAGNIER
