### ISSUE TITLE
lost password issue

### ISSUE THREAD

**Issue by wouteraddink** [DiSSCo/ELViS#90]
#### Description
when I use the lost password function, it seems to not check for existing email: if I enter an email address I have never registered with, it still promises to send a password recovery email (it states: email sent). but I don't receive it. It should instead put a warning: email address not found

**Comment by vixriihi** [comment]
In security perspective this is good behaviour. Otherwise this feature could be used for phishing the registered users emails.

**Comment by cannedit** [comment]
Registered as Redmine ticket: 49099
https://code.pictura-dp.nl/issues/49099

**Comment by cannedit** [comment]
This is not a bug but deliberately implemented like this by our developers so that nobody can check our database for registered email addresses.

**Comment by LarissaS** [comment]
I tried out the function "forgot password" - a promised email with instructions or new password has never arrived.

**Comment by cannedit** [comment]
Hi @LarissaS,
I just checked and it does work, so please check the spam filter of your email box.

**Comment by LarissaS** [comment]
Found! Not in "spam" but in "unwanted mails" map. Sorry!
