### ISSUE TITLE
account created email does not contain link

### ISSUE THREAD

**Issue by wouteraddink** [DiSSCo/ELViS#92]
#### Description
the email confirmation when created a new account does not contain a link as promised. It would be better if that confirmation included a link to confirm the email address (would need a change in the steps on the registration page too), as this address is used to identify a user. When we have a fully rolebased system the validation could be partly on orcid id (no need for multiple email addresses for different roles anymore), but we have to take into account that VA coordinators may use a group email, which cannot have an orcid id.  So the group email should be linked to the va coord role of an organisation, not to an individual user.

**Comment by HMHardy** [comment]
Yes I also experienced this - the link shows but does not work, I had to use the link in the footer instead
