### ISSUE TITLE
Uploading of documents

### ISSUE THREAD

**Issue by mtrekels** [DiSSCo/ELViS#96]
#### Description
When I tried to upload a large document (250 MB), I received the following error message:
"Something went wrong, please try again"

1/ This error message is staying, even when you afterwards upload a normal cost sheet. This is confusing, because it looks as if the subsequent uploads are failing (which is not the case)

2/ Should there be a size limit indicated?

#### Steps to reproduce the issue

1. Upload large file 
2. Error message appears
3. Try to upload normal file

#### What's the expected result?

- Error message should disappear when the upload went fine
- Should the error message be more specific? Or size limit on the files

**Comment by cannedit** [comment]
Registered in Redmine as issue: 49053
https://code.pictura-dp.nl/issues/49053

**Comment by cannedit** [comment]
The limit for uploading files is 25 Mb max, which is now indicated via an i-icon; futhermore all most common file formats are allowed.

**Comment by mtrekels** [comment]
Tested according to previous workflow. Expected behavior occurred.

OK to close
