### ISSUE TITLE
Renaming Institution

### ISSUE THREAD

**Issue by mhirschfeld** [DiSSCo/ELViS#98]
Rename "Museum für Naturkunde" to "Museum für Naturkunde Berlin" (official name)

**Comment by cannedit** [comment]
Changing names of institutions (and VA Coordinators) is a bit tricky at the moment, because there is no functionality for this in the front-end yet; this will be dealt with later on, so for now we only deal with this in case of really wrong or messed up names.

**Comment by cannedit** [comment]
We are working on connecting institutions to GRID to avoid having to change names all the time.

**Comment by cannedit** [comment]
It's now possible for an Institution Moderator to edit the name of his/her institution, please test.

**Comment by LarissaS** [comment]
It works for me
