### ISSUE TITLE
change Institute name for Museum Denmark

### ISSUE THREAD

**Issue by wouteraddink** [DiSSCo/ELViS#99]
#### Description
The museum in Denmark is currently listed as Statems Naturhistoriske Museum. 
Correct spelling is Statens - with an n, not an m.
But second, it's hard for non-Danish speakers to figure out what institution this is, so the VA coordinator suggests to replace with the English name instead, i.e., Natural History Museum of Denmark

**Comment by cannedit** [comment]
Apart from the typo, I think we should decide whether we use names for instsitutions in English or in the language of the country, but not mix this.

**Comment by cannedit** [comment]
Registered as Redmine issue: 48124
https://code.pictura-dp.nl/issues/48124

**Comment by cannedit** [comment]
We are working on connecting institutions to GRID to avoid having to change names all the time.

**Comment by cannedit** [comment]
It's now possible for an Institution Moderator to edit the name of his/her institution, please test.

**Comment by mmarschler** [comment]
Tested, it worked for NHMW. I could edit the our institution's name.

**Comment by philippeloret** [comment]
Tested. It works fine
